travis:
  secure:
    BINSTAR_TOKEN: 7aIO8V1nHTHgU4d/I7vFLcFMtWaFg2wpKD0Ur82XqV3tzaNChAww9LRlc5U3lAGKzBfXwf96KIFqM803273cyiBcWcELgqGr9i4SxXvbMgtLApwRZhv3B29YkzL+COgViggY9IgdN4Hi7NunTW3LEtKxiD9k0D0hx2s4XKVXQeOmD1o5BuQ9JCnGNLHPaUAMPvXHfF4C/2Uk7j2mAgrJe/KFH0ceu/Bdefm0G0xSCjdbXh0WOxWgeqD0ARBtmV7c2Pgxw+supt1TqURCu39Sh6iZJ002/Z1W687XchSIi/0iLEMAFXwHeePqtHOBbkEBwL9mAAcmPtOlKuVjCxE1++XM2lIvRg1ubMgZy/+2Sypum43motnFWNA5YCySWGWzxiKqa3Db0qsZNRydo61+4FE2nalqFPOVyICJH8VqeXBqMu8SQNMdfFnQTu4wa8fWbQZnOykfkheIxTaa+AB0dMoBzgApFpTcwYJm7pa1/7X9+RGx9nw82SJB3223qhKa+X5Ij7wmNpC+QDV/BlK0iToI5cw28WWevefB39ChlppRQTIAvrljLYt5YzgT5GkHBw7jdq7QlDBjJr1rMfSq2eeMHKJoNuk82x3XToB/It5HaOI/KGmuH+UzCp3iUH2qAcpgOw7pciLMd1S0iyG+7+9w0e8U9t3AGkUKoPX7p9U=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
