travis:
  secure:
    BINSTAR_TOKEN: ecgxsrjFTgvRN+ptSEbH1IPjsXyl0qilt4Hn6VHS3neV6hjTweYa0UQygop4IL6ZvECw5IRm6p7N4P8VLVkwCONHjJBNLAYz96C7i7yb/KDAZy/IQ+I5VIFPjnJRMB2MgpCq5Q/amqdglw6YgVCcXWzdC5xF6me5KtWYer00w6kMC4XYCQhIA031lkTIhkNIz81sXqYQ4B3q3NyNmX9PzIZuhEVtijVPGk+ZLKqvk13CtN5ltebF5mDY0giOFHrlngZVeMwH5+y/9RiKuAhhO9h04+n9ygA7QcPmMlpCcs/+JpuRqIdO1KHTLXzypG2pLpHa7L9c1JjIynUi6xXRU9QfXLQrcpAWXAqxEtZ8kFXe24u84HrRtGBbq9kILbcywlSkgUs2K/3yHCbhgtRxMG0R2JrRo8kukDchwQakvuCDMal03ZYD9EV4flqFlO0d993+zrAgbXlF58Tt6pDBXxfn5pL/r+hGVyBUiF4VTf2PZn/1ulSFm0H9RgqT79pEDU0hGK/gncBEDG5L4SDnTYQeDIJR9Cx4vVwZRIC4BfWyi7z6fSyJrwfOLQSJpJk6Rv6HT5uXU3cL3z8jsyIiGGseUFlUGnTlfVSvB0SUgtIrnMxJ726OraXty8imqxdjbfdp3Fb1HU09TVbmctEEP39kM8qdudGyT2efPfahARo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
