travis:
  secure:
    BINSTAR_TOKEN: AE1Ywbzxwagiizw62NmqmmXR1zULqOytYp2MHkm39kxrI1fDcnhqJhj4CiuUQzhuH8zqxU74xu7KKyA0jV9hyttavWE47Rm15/1uRyocs4Qksz9ipyHVK+Xtj5Ti7DUycNoUPZon6fZwcZcBvTmJV0Ai5FfDYC0PWRD4iwxp6Dm2cj0U3c22OUoF76H5vxgh8VmaGIrw4bqP+7oP3wOs59I4+nkkttWSHHGBh4znuLCHmhV9NNU4z6sndEvoNXnnp7ZI88NLj5mBbkFEMBEL++f12BOmDtXHrg5rk0NCv+MuYPOciyk8U92dDofN0WJD9XQEyWYDPi1l/3XPheYAFcWiKC4F2VnX0wshnm/3Ys1Dpa/sc7NtkBAg68+aoVWoGEtRnxf+YCDLAH3g22ZKqC0q1DKe0bKI7yAM7fgh+5eb9GNmE0rxYJgauXzWDOPE/hfpfPBuVzFqZ2ibAdv1HKBwegHpSZxgRy/97je9Of++ebMTDqDu+AwrIdTS0LGLlMdv0gUcBnOgrsxyePBnVRsdPMizT8JJkxTbx+oOE0L3/v7I42NfpqdSC6G4wobfCDBptRolTuK1c+T13nDC0L+XSlQJWT6squoLjV8PbGMW02oQFXt5tbWUSQUTnfUMKivd1NxOot3JsAKujcczGT2r32TCadtvpbgXvEOa3A4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
