travis:
  secure:
    BINSTAR_TOKEN: DPxmK5W9pKmyD/FqnDz0OLhPEa/n0AoeGU/vjlxmU+4TJeBaolyq+RAPEchUm3r+XsBP8YFk9nNKbAYflt/WU8hxhi8k5Js6BbheLX5+o0G8XnpyjHHxr2NyVaucsXSmy96VXAhhHUjsUQi+z/LQpMe71Kx0gQgQJ0xQ6zaR15Nu+u9ycP9uAQ1S0EpmWeU/q9DhXel/tPhINb2IauFtm8AMMTAqKFILPlk8KQvtC6ABynBkrvTY04B2h7UdsTRVe+kcpbNox68f+pBAKScSZQdFe/Yt4BTp5P0UAtvEaaOJrkleCKyDX7baDXMlK7PyGO0Lu5V3YfS7X0VGUH/WP/PNjEvCWbTxVEmGpwX19vbb+e12oaopAvGpWiUCippjEoMO9zrI3X7Q9u3X1Qz2iBQwdY0fX2av1JC1XlpE47nwQTxxPB36CUt6Pqz+VcSyq1szAEGTcxqzdWz4R9aKW/h7J3HrL+lSe5r4Hrr/oLIT/JRxipy/rOvx3fMB7rItpSk1CxnKqcBn/5CBRrxG8Nb0kp9GN6JSQXWHQoVZeuKbWdsE7mycvWXkhGs/RDw1iAQ0/tezY1ToNQF4iCF9s3qsoLMZ0CKV+C5X6WJaue+97BSSzlS8eJ09gV2sXQnmHHt+dH6n3zmaoK95iycXFa6/rQQFvskmo+gzmk7ynbU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
