travis:
  secure:
    BINSTAR_TOKEN: hDzHaFnULEl78PKQHL81yKX+l733CHiegair2NmT1QcA1dT4Me/0oWBXU/01/IUkUBRwhTgUDceyV4RLcy9RmxnE0Ynt3Pa90QwGB4wTBlSkkf028VHPdiS7xEGriN005yeIAGBjWUqbEHgiDNHhTrRfsYdymMd+94Dl5kqiQLh7+/OG8fZ2Ipk5wpXvGpSyWc1zxsg260j7yWKBxCPSZpHopl6edNh3sSYrTdTRokqHWznaWFvcWS/soX3ZAtATriqNpfhBwBGIDyCw7gZqTQ8znxmPtLJLmtWLd7mqaXYgenQIjBFE9TG7HsIo5r7JYE6qJjCClaIScP0pcucCeXgQvaPe9B5vHElMH/D6A/6onOCUmWYOJgyputS+p0JgX89KRWx7hUGLF86LSMvkrpSBMjrOaNpiZhwd3NRmS4D9Gyjagz15A126z+3IFmrmuss5nkADb+IbAPwhdwTCR50KqDzomIiT0ED2RtMT5/qfc5UhdfnkoL87qOKMb8J9hoXgXHhjJxnXhoXMSvtQ5tRK1dTTwFJefmwFXC7X60GNweYgwTaJiUyMzk9nnnYEaxut2thZstp4S+5A55SSocPwyK5AiDvYXLxK2hR+E0zIZNQ1szG7R+ViZ8eDoVffSnNFK/yodu2NQauB0gPb/iWzjAZYckio+oin8NTJCNU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
