travis:
  secure:
    BINSTAR_TOKEN: DC0wTVH6XkZ/F3bWvtL3hWDgQGWR0TXBL+5SYC5UrtxH9gQFvoX32iKV2KWHZRTdQlGHW3QyeJqPCZstJM5uwP8Buok+Y8vYixktEs/NXzYsUNP7uxSEhkaKacVMyQE/A4uShc9xxwZL/GOf4z1ZD9zqK+Jz/yijM3umOfcnf//Ij1OBEx44n6TLUNATt+6TkfCu+DMwGZO06agrLc3LiG8YejxNq/86nKtMtm8PpLmS6FVtZRjVcIOG1wYb+r+JEJe3GXLQBjyMnxImL3SXFE1We+RNkhviHW1UxXp2QKOWfRYAbv61nqQdAhr/K8YDfXXOpUbAtfkGttfqRtbIz1bSvJQFF2r6x0XDCy/5hC6RLTogUR2Iae3ZVDJvlThoDfzLYPvH+GjVeEH7AxpYJo7Op+ykyuRQcqbHzzqpG80sdgXzcofxx3pijKFhVhiKm8lPNqU0r72LwDE943Y/BDyxhWTFSHyIUXgpfNZE3Z7MOxR3KcM3AO/pdgijcYkAkwp9sm7/xgPo4aEpZdVVxMw1hddACfT+fkM+p7wGvIvFg9NNCQ27g6WL6ExWj15BNJxI0iKUfk7Za+KfR3PeStDApjNkK8+kys95Rqfscu7IhCLNQ0wOdntH636dUKkty8HLCyDZOXXSe/CpiY1PH4tIaQ35J5k8tONlPRiTmy4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
