{% set name = "nettle" %}
{% set version = "3.4" %}
{% set sha256 = "ae7a42df026550b85daca8389b6a60ba6313b0567f374392e54918588a411e94" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://ftp.gnu.org/gnu/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - dlopen_test.patch  # [osx]

build:
  number: 0
  skip: True  # [win]  

requirements:
  build:
    - m4
    - gmp 6.1.*
    - toolchain3
  run:
    - gmp 6.1.*

test:
  commands:
    - conda inspect linkages -p $PREFIX nettle
    - test -f ${PREFIX}/lib/libnettle.so  # [linux]
    - test -f ${PREFIX}/lib/libhogweed.so  # [linux]
    - test -f ${PREFIX}/lib/libnettle.a  # [linux]
    - test -f ${PREFIX}/lib/libhogweed.a  # [linux]
    - test -f ${PREFIX}/lib/libnettle.dylib  # [osx]
    - test -f ${PREFIX}/lib/libhogweed.dylib  # [osx]	
   
    
about:
  home: https://www.lysator.liu.se/~nisse/nettle/
  license: GPL 2 and LGPL3 
  license_family: GPL
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: 'Nettle is a low-level cryptographic library that is designed to fit easily in more or less any context'
  description: 'Nettle is a low-level cryptographic library that is designed to fit easily in more or less any context. In crypto toolkits for object-oriented languages (C++, Python, Pike, ...), in applications like LSH or GNUPG, or even in kernel space. Simple, fast, extensible JSON encoder/decoder for Python'

  doc_url: https://www.lysator.liu.se/~nisse/nettle/nettle.html
  dev_url: https://git.lysator.liu.se/nettle/nettle

extra:
  recipe-maintainers:
    - Cashalow
