travis:
  secure:
    BINSTAR_TOKEN: tgmAblj0CWgPh4qmK1Dvdl4EnUADj6j5iJDMpogIoPiRsztpa8ncvVW7WCn2rVN32YRbaBpg1Vw0ajhvqZTsXCx3TA9EZs3Qg1Jby8tPuj4gLS8L0W8/g5GWrQ0iLbjoubKHAlxTGPqH9jnGo9eF/nQgskWWP5uBjAJlVIN/uLpf6HrDJfpiZlJMoaq7GbHzZPM8BcWo+HL7oYuWp4te6R1WMMbHV3PIEuLqtxRIW4WjDMwuiWEpjxC0WLhqLuvDflgvFvaDvaB2nCNmg59z/aR9a1E+pKmT8tTmCovkA3oWQw/gfytboQe4rTuNgOjxF+vP8pEEDH+kbudFj4N4dbpYSAxk1SoZZ6C6lgSXB9If5dtMUnRuvA2cyX7D+EzxlHvdIqfsXFHmTXtANDEXauZ/aVL6fRe9P2Ea5JmFtFDX/eOixeAgJTwt7907loqfYcpGM6QXmPFx2z8I3/RUHaIceg/SHjnE3MU3lXTii4tPYjMja9kRjjTmBfcM+o3/HELB/ZadjR4eucbMt0NqqHcRutvzlWfHk3txSVfmLC1g+G0NGRSUKgaAPFho4xhpU6I+/LwiFqXVeF7UzkS1hC1c1zVSlSBx19JLPe92XqMbgL8qQL+mhBvU5kN4e+VmM5FhZ9dFiWUX6zUiOqeO5DjFNnYEBVWPIk+BlERI2yU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
