travis:
  secure:
    BINSTAR_TOKEN: 647DFxdX9NpcertTVvAxzfOJmgq70QgIE2JQz0sBNqbr69KjzCXbDhVfh6p4ohvXT/pF7h6n9wkiyFc3gsMb728uno23nzDJwaxmcBIt7HoE2BAL/8PM9a6sB2Z5upDXJ22P5aWAKh0c8WWcAjza153WqQKmILOfYRrHBk4b255ytofsHQ4oimS7IXD0z40OzEd341BBiM4E2Y8GfMUlQLwfqDpoKbas7gy51Y0pNdC4yTznIaqj2GPQ3O7VBYK5sYp01i1qgkrJnfH5QEbn/WrU8ZxaCKRhZh7Oddhj1X0+dZ9n5D2AC5QjijDD6n6kWTLt6eYnMMKsEfy/r8md+/X/SqTW+dWVlirtJC0gJ4srYPvbApQjHJjPCpivxq9HhLXEDAv6LxI6eaP/NPeXXWV91CxnmJ2hk7YEnCzg1lLGwA2YBQF6LZsLB+ReED3b/F2yGQEOKpV1foNIyjNB5M523iJQNfclPQJNJbYdELcmVkKA0fhFYJvAbTY3N4p52WGd6ye5HgX6N0+eCfV79oh3Uj+BU1xnbHt2Kzj3mCbBCfpROhi6VT6rxKR8GcfMDGEy503mHR5G7LkibLyoOUe7pLgU6I9xrYPfkCaDPTSa9oFL52dNgOjtPRqKB6nr2WJFTrQUB05He4yXuEC4Ke4wjmr6A/TCdR02H4j4hzs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
