travis:
  secure:
    BINSTAR_TOKEN: U+ha4hcqhR1NbYEgT9RaLgjyWYnwY1D0rgihVp/kYl5KS4BQzAbvOhp65TQj0tK6LwxO6zkJMFjRy/9E3TFnY/rMLsUJLZFjgksU+gK9nEQkw+Yh1oOdWkgOsbZMWHulhnt9YsSssF/l7NwUVGAvyF9Y943zvX7lIA50uZIE2fKNWpeAOrkYFvrHbA9/DdLeVNuvbspNsbR8qSJh4dq6IpyblJEjm3vTEAUXqLIddunUln6g9VdM6Er48wFKM0FfiR4QsoAHYM2eDf6Mi3nSM0M2gwuGEMRFXd/e1xi/TliDEBiUG0XJdr17RgPRj18Wb3VTnNaECKtAUKE7rU4KdRUWphi56ySpAtW41vo9bxr9YslKPTQ9eQjqJc2d4VIcWwNrOyL1/GZGqytg6CiaePdTgNv6BUo1tMGzRt7FkUrIPKylR09MlyHqBqMfuPLNmMPm4pO3oAShHKcnKoJJnswdmux83Bn5jmrsHu5Ipu7Lo+UIXCHeXDcKb7Lo5fxndSRq7eRata5bD2ssdEh+rEdGTzER79GGO/s3KiVZTcJOdiual4OxMKyY0vpxe0jegkqKrb6z2FpCBfcsds5YF+nHl9jZcTfdAELXjw8uVTgvLt5rPd8Z+MSirATyE3mpTwTYKksSYJeWq8BAGZNagWIXbTw9HyDLINi8HfZtOKo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
