travis:
  secure:
    BINSTAR_TOKEN: BQqDQtcPcHMaIsZE6SlOBeHlzrV91K+4Rb+cI2+zPbTIh/p2F1WsgHtsmUbKwuHNlEQn7ta8B1A6zciitis7yl2gFxnCAU5H/LZTkSFY9tXvsV2oL5tc1C+6vadfbvI6XImsckGaRhrYIy4AlqK+y2qqYf9C1seR/1JjuFqs1Zcoo99J+ZacFjqV81MUP68IFVgj9ykAPkzM2+hlq/oGrcVCULwtLC5pRk5d6XdRaR1YiDOrbdm1VbagHaEZ6z2y3da1BUxfxsLQA7ybcXXbILu/HsxWn1t0fD2sGRnblAb4oOO+DycZJ7FPD69q6UipzJ5IBtmFa4L8SrQmRqVAgi+Bn88+vqzj07nDrMy/ouN6IVDZsKH7L3lt9e1/y2nBATPzosv1H4p2HLojfZSPYRaqCqqwn+SQMfczSfBM0Swst4p60rxiTDeqR34fqiSUqYrEenUMvykJwyDAvRu9vIGmfKiHnZIkewpNLhP5/nAQFhyIeUWctczOvXteXtfR3DEpXVwEge3idi55s5JQZC3oYdd0CAsK+jwrXvbPrqD85Z6qa/Z7CsNl9wNs/NbyQjBm5aA4eDmzJhKPIz7y+s5xxA+mQ0Og28konXZ2TseTvyYs4iGz6VKmk+dY22OU/L1hOCAxC8GujVHr6yMnWzWRSw+VxLBnnd1pE8X5pU4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
