travis:
  secure:
    BINSTAR_TOKEN: UxOe2mF1ki7/EtRrVhNJEa71Eh943kG8XAA/K0Yra4pRemJScaTMGsfGrckaw6bzfF8qt6c8pVjFVV3YuFSrGlvnYdEQWMmc+N8p0y6eDaKkx5r+O73Wp++3EKDiYYJgbnya9F+Twb2dC1KLdC26lc6tkxQbCqWeAPRWdR0tGUdFp5uWWfEkIGaQfgjzHXF7thBcdPb3zAziNaSF9ZB2lwFWeUGxpIC80dCj9/XeNLAgaTxqDwUYb0JeGph3gtPSB5ChFvTsiHe7EWCtYysk/VMCMo801k+k3cCFzzGMpiraoBxUEQxeUgQVRedjvf8Od1c8Svd6l/rY4/Bfnt02+Pz/UM49nFoHMy3Nzmw/T1ut3+8YT9lU330qoUO5TTaMJXNXNqgS/9zGXGP/aHcyXisVx5psqH2bAiNaYTvwHr2EOUI8qf95d7WALkMK3LccsJx2UTcnlEhpKP+51x08s56CDazZxD0Zt5bSxuBGQm8Tq7keGZStLda6moGGVCxduIcH7r/9rLskweqiEDvYJnQOhgEaHNPaYtmCBrUDGBN0NCFUlgmiT5BtDyadgClXuFycFQaP5e1vbqNcFXRoEJNitu8XjB/PeunMjQoyawJG0/XRxqdKfr4hYxfk2hP/FYVESG+KrU2Dan7v5Ty2BqY0jYWK/Qta58IVBkrvIWc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
