travis:
  secure:
    BINSTAR_TOKEN: yeo6acindKwFKarnXPwZ8zH9PWgTfo91FtI+bGKXkISw4Qr06DlYknFZL0w+b00NAcifUMg4gLIBitoZk/tPLkh7qaaoda4aZckgS7n3n/Xz/UoibQ4HBwet6jqxApzD2kCWQ0GBM7anwS82fKOs0GBejXafW0BAxn5FaexoArP5IF682fs52SPfNXguNgzdMESgjYK3DNuDwrgVUmzuJKPBDDFgq42bdJrdzQD3SzavhOTxHvtq4G3OLvb4vwpRbcmgR6SAaC08Ou0sFRsxf4JxahBP9QAncZCf/wX1829Z656C8iEMXi8ypKignP1b2S3fv7HFVPT23bStf2iKNMR+syD/IpabCJLZLfDA4Qm3LMb0etQlmwIsZ33KnAe6UIAvw9iDWzY34T8aRok4xCWxFU96JLBe7QMOccK7j9QGZQAfsxW5W65Vkq6BOPcZ8zh3NiQ2eFbYIYdqHRykhx05Y36kyAaWRrfAq3Q2cwakPeu53wRovrQ2QAnAw1o2/lU2ozRchcZvZ6sDEdKoshiw63mFGt65I+yjfq8TP1oBZNxBGjyuSssbniMlNkO0rAW8ET73Ij/mBx7FHQs22Xim9BTg+6Mf7+3+Nv/6UkoDxOaJ7oHILc1IZOxFJyWoKMDZz+3XpwL7thWqZBpKNG2QljTlr976vbxsnzx1/iM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
