travis:
  secure:
    BINSTAR_TOKEN: PBFXIC0JduEh5uHNkQYF5ygVonBA0ZWUKIRswH05KdZPGXWPyrdO/8R2dZ/z3GbTtSIwc3hv8EHwN0FGhcoo6ADenW9xo6Nx/L8o/ekQFUGijkoMBrNrlhvBDm4As9hDJXtf8buDdiuuXLxaKfr3ZDIyzDhJ4dgDOs6VwvUmVOUg7qX7SeDi24Uizu5whaZmUV39AMorhlzLekKdTLPEuGkcz9Zxs+DiUxiSq8TUaVtX2ej7gWk9otTGH9WS0DmDmoe3avmAATy30BChwwYQiTj0iAh9lGYd4A3oTQp/y7+3Aw1ZWgsMjCurzOcZKlCwTicACM4jgWfv1ywpCVX1sSxQnPiy4MUvqZ6KDVCxFNxsHHha/SgTGTqevEy4sgdGo/gR30pUEniiobb6OmZbSXhSc0hrloBpmeEM33VPayfTyeWvwJnsyuuBGbX7WYWoIH4xhuhsuT2xiFu09BkOyzBoDPa5w+l9E3u528ZBVc8AWp1l2wd+TD8/oWdVD5NtuETHpTCMJJLxkNhIsnoCxQGweAYCAkMN5oiyf6pc/MD48KPMRQyxarwlSGjRWBkAxG5KsHewhyNywbRISrYdqqKPJXyV9yWU06QxuOrnzFMsSwAmg90hwGwkrAJIvUcxGp3du5kiiDWQWRY9Fu0zbIxlNjpTRaufuDEeKJqmfMs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
