travis:
  secure:
    BINSTAR_TOKEN: EqTtd8LTP0QVRdwZkvB8sqx0TzuJrm5lGz+BvdrMr5jpytoV7u4tVSjZE7SlOvtWW8R5cxuspzh2A4g6GsLexseuaRCl33OSupTX5ByOnx+9ad1WG3eaKaU0lD0I230ce3L+Kt+A0DK6hIL5yRaYmb9TkHk9Dctbhqje/brq7Rzda/78Tc44Fe9JMPkyqypCqGpsdQUyUzKDc674q2qUQ43UG+lK3qgfqH7DQ507Y8j0NwWWjL/0bPWZmAWplQlf01luXmBDJKOCqpFG456U7m24ExdR/i6vuwWrm/GeLG0b6ks+Jib8LC4tGOxlJ3o8B5BRTOkuk1CJ9vik9j5vphFtv8G0dU7m6mTT0ZY+aE0gy6uuxd6sF/xGtNuKj9oyhpMeFdpictLNiyZqr/HBxe4CTbuAHuWkgYF2xNLicKe35tJ9Uxs65Gv6xVS4bcweEcF1ERMJ48qRg+OTzP9Wc0jbZs3mAw9ETkHPjPSqmeOee/pZA9P4xuYsyThWOCaoUEFafSrvRbc/6QZy8+GFP/UffRCOd5EiaH62ZXyqgynBbhMklk17PfsIr8XvoDswi93iY5ea+eyvvj/W8c8iuz68G3RJbD6OsM2H7Tl+2JohrwIhjeaPwPQQJNQ2J6V8aowaNxOZAzV/ljaO4KvJrYgzlAUuW+gZyByBoMVw1N0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
