travis:
  secure:
    BINSTAR_TOKEN: jjrH6Im3ut//X3RWBnzPTJbNxKM31opuy/MlZcrzSS4SGw1fLb2BDt4y1hY00UJmNSw4mLgj5HRwKepkP6OCMsil27Lqu/KDJjUJm8nIEX8yL5UQZhUgQm7xZhHs24pXsqh8D24595XvqU4eJ94YTxyf6Z1zr/URyGxtP+HVE10V6k256ouCDKhAC3Lgif1vEqaBsmEr5/3qAEXSu1xi0yrzUAfVqAR/Jy8lzVTGvsUY/x5h1TsK9LgaejSMDnCF7nzUe397xG6A16GbXkFPHAAUWbLkwJtv1zlkW3BldaKHhPDO2P3SMZCtyBs2VIHui9SthQWFJvuwbko7OqORK8cSw6Uf2lrxOJ+9jhcZ370gKNobVWAnyYKI3kcMxnSh455onHjX8EBT+op32zcSbiTKPb6RoyZ979PnhzjmbtP7EsB9HaWmBh+whnHxsrNcVFnGpefjYOpjJ8uMrfjWrLP5cUKUyM1LUT7/GFPbLntCMTuv8rZSfehsZ+NrnCeBIk9tj/lh8hgc/yOE9QaMaEWnKV5aSfVzuVLGT4YggsXfdITskraV47sjF2j6HdEUdeL+PVmqX/X509NYmPakKVSMTtWXIhSGzau3T7fZ+E5Fd5NCc0ehV4zGV1aom54g7M2r7cAjeAu2uJ6sdW4Ru26wtF8ryARrjIlf9uXV6Zo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
