travis:
  secure:
    BINSTAR_TOKEN: Ijlg67T/c+4mqFXN3QWHAdrpLOnPvXCCDTwu7V1Dqa7Ss4wy4ybCjd6rJN1tzwhAqg9+AO0dS1M+SoBZ792UyHc20BRGfhpLi9lS+b4D8hxrc/fHekNTmxXV/flXs9sTEMCpGZasXLBlKTlhdBGWH4wRqTgLZfdBHBWBtsJDJJ4uGfNKw0Ge+QlXIJjdTbP+nBecZFqkdvF0trCL5eGt3O3ywL1xKed9SijsjGCG/Rchdy8/yPOpE9DjAwObtuk1iIb6h8kSzaeMpV1a2aLBmYbHj2N9q8RpThzZumPtzJIdecAt3Vh6rwoPp+xkIBLuWSFEtlfT0GxRAlotQT42E4lGCUOrjhZDmB8gO1Lh28FtW16b43B+JlWGLcmg5AG+Dfk3c/Obd6z3kBbZNKjPfWIWZ7jaWiCG/iLIg5EYS3KcAxD3QxCb10cxLpiSuTihCTVCXoNt0EeU3yBG+iaNnF9v4zGIJW37YQuqjH+jvOSh9ivxtoE5iYmarZ9HHLsZsJvQ498vNAfMp/U1CXC1x6QaWeeIBBIYGAgbHP37k3r9Q0mNKadbE7X4aqalmENEu7eGMb/JI4SETlRgAQWYocmaYHqujnE5vAvQrHxqAtgPp6m2tTzjz2NE17x2VdyrM1pMePH6fRR2AI+aB60H98E5kiWTqx1Ky33onKr9N+4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
