travis:
  secure:
    BINSTAR_TOKEN: MFpbrOrfxgRkxVdG3BPuPxnZyRjBc9VerLstV2xBYyWJ5SBex+imUY1yBqeDw7CsGSWYqqCiBH1PHLJEhQyihVVBNrJOsCFMAHgu5AxBMHTC1vvA0w2kcWeFp1UA5nqW8irNTRmJ0rlOqEcjrR8K6CCz8CTfIquiUTGCaAFIuMMHowUMr/M9A8eg3yJ9E/7cerKi7oO8y2vuuK2yMnltUgNcSU67d6eZNqU6q0cSFvkr8uwky0BIp9vYfn8zcnhmOum1X7+XwHen3ZVsfzC0X5YMpoJuzvJrmDivQ1XhfOTp015kURUuB1Q29IbhnGjjlcpH0mQh4cNrkV3HFeBhrF3inKoE4u8GXjkFneKGPApNx8d97A1tb6NMYPwwcZhr+SqKlbTNXKZyYx6llSgc7aC/CsqxoZ1/rWwTs+n4HZiRaUrmVbS/Pgxqq6xh/Y4YUM/K8FX8FfuWaqm3tihPkdJW0EDzUsl1EYRmcmI7jeHMe9NiiZxgYLAo2CbQlYyEfUAyFUhL3FECo8qfJHStMoU9cF2ikgQdD4tU+RZgpyCyweNwDD+sDmYV8SLAK66FJM3D3bx7mYuIMcI6gd5jp9ZYo1yV2srSLA2di6xcasGG6t+i5XvX6f9OgIwp2+IUnVgAjtv6fEJdWum7xibqhIeTy/THAj6vE/JPc8gQ960=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
