travis:
  secure:
    BINSTAR_TOKEN: kZKO6eZgMGzNyluPM1ArANUib2TCvHAesSL3WBBqG/4EenWJyKSB7V1lQ00l5qsM8fF4nbW7IJFxJnLFVFMmVbJO8I40Qk4W/LmsFY/QrY6fI8ibnb9LXpj++Mc4tMuneN2AXwUWI78qwpvHL8/ju07V3M3uWEsypkN+xG5FQBc9O6d29yZ2GoMxtgMC3kMLIiQT13pQUAb6NXEjo9ZFc4xNU1KH7izs7bPtvpFGVg9wmUh56XtlCcE62VPHIM2wmxSghE4DcvRHpGYJqrL76KtoQnDpEEj5Wg4KHYurzqOw2RKwG2kpOYT8tlWIYVGHvUC4QsJeKcVVET9JNThKvBDcO6xRfBioSXwzLVbwlW6mddFkzoxrvAnKu1+3ZkW2PlyPL3o+v9B8W1euolr3c8wJeejfaA+ASDTdANM488fmYb+/u99bTvFXVP9aDn/mgrLozMh94UMZT2A7K3/sB7+zbGGuRNxvU9ukMpl6eNHjD0FH2yNFPb7DmZFpbY9sCJAKoHsWKwsCGjAnjhgyl3cUBF90uJdK2w8BliLGZjeUZRGF0k211nDgpbtSDJHpoww7tv+mzJdPonkBDVmvgoHG3qxZqg4IQGBsoKPowrOWmkyJ2QJelEM9uohbDOFOPO7LrHAB55bQ/18q3+uIyg9DXIQSNXII9MGRDQP0cTo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
