travis:
  secure:
    BINSTAR_TOKEN: S8GbsAp4q0p5EcegAbXL6XgJ9HwSuu9C6jW0I8eKVq3L/ZDNi3+0p7DTg0Weljka2yFrvQRIRfv5HLXNs6Wf8BADcP/7S5cAg/hKJxG1KH5xXLFax1ABV8SyhULqZVXfRpdd5Uyq9IGSZpBtK/cVg1IwZi0uonEIEVYlNHET9LOuzGH6zbqAg5tlPHcOSR5VSGPYUqn741ZZmPbwUznN3fyfdkB1Dz883D5MpT/2WNDUsRKgfnqR6omP+/vPxpRDaFPFZzCH00JmPBkyxF6IwTXmj1EUdTTQbTu0Gx4TA6PVZY8oGnMCZLhRXDzxt0haC1RhoxU572DxjRLwc5iD1ZPfgL2RU/ie0V2/7mRrRlq2gu03TqLKH5ochMEKtqpKFQ9FihOur7PdzHHlmHq+TR5y9GvCypj95VjTxc2ycuH55bABglVGUYoZU/acglS9u7MLlUFaDgu0MTn2WusphG01EE7k2Tj6Cc3MiGlZkJEkkh7Yg7OuY2+DkhSNRDUHGKwREm79TX2WZvNF+4hKRbjL2PuT1na1fZ8h1pWIyORli0QVXDcbPkEPrQQBNCZA8Fh05rZm4VT3xx4UchPBl2it8wfp7fMpmFfWrjxENfyTA57FyJu2SSVCtoftGZ6SmLPWuujNSFZk/w9lVUOgkspumzONh5kKGwobzDxUMnw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
