travis:
  secure:
    BINSTAR_TOKEN: LQhV/um4MHZLGKsqv1/RYTO+X8/mFV/AFHEpzYstV9Jy4mffh9zSEe535DvQVoYyBebRD1CWElCc+/eWGlRuVvMQHwPhKvwFYZQ3ExyY49ms12R1k5E+wm4VTr1/QQbBO1ZeOqxvcYHqNPeOMudnMSWqn/b/GY2wROdt7yVEiwUJLftSQoKBhGxDKJ20LXIEpGe+ygc+uOLBzPe2VzV5br/atJbg5o2a0Gbp+tZI6X1VQZ+fHPxoZW256tQyhsv9Ye6dkXs4VUlG8D49YkLBe3Bk8f3ogBLqP0BUC1Ztupv1AYBb3bDEybgfYouRZxgTIyc3JAyA02OTrt5q5ZrX2mW8VvbIvQU3islBeSjJMaEC8gvBSSbbBLRrCY59hnW2WyV+Yubxcmkuw9qFtNOk8YAoVjdskdspMIh36+2ULbOKxARkHZd0GcmhxvlV5v9SImhnPT8CDdhe7C7mocWshQ3rKJ1yfy3rPpiLNAZjVbng0QfYVOkcF+nL8O+hxU2Xe+T+c+5z6reT0Gh4qS2w1NZZKclEcYV0uiNmx+FCQxaIj0RpEuX7/v/glWpPH+ca8/dHDK0fmULXgFZ40j0UUvThLZF0gS2BiYWX9Cw1jkY6IvoPwdL2pM0kj7eZsL+5SpNh/OahxNgpMcdaTc5LE56OFzrAoQo7MlVRfjPuOYU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
