travis:
  secure:
    BINSTAR_TOKEN: USFYXHAKwGZxTo8ITqxxyF9v+qf8MfmVmtPI6bYIKGUuth/C4w9hWRUHTC72u4zYx7/+uUktXElj0uEqI8UOObA5mnMJj4ergYUzT5buMjs0pmBchrEyxh+MSmkg1YwGp0vx0QfBHb1NoVPkbFXwtjlwRAigkHpBi8+MYQYyDc+4IgsFDMUZa6PBQlU4GZU349vKWjKtuQDMTvXBVzkCWZTGaoh/cgmSU78cbj8Meu5+VwlWCQrtvD5yaWP6RzP91hlalkAXbijtVL2q913u8VaNJB48JPYxl6PLts5SWGWdwUQp9if3aySVz/Sbzp8JggyTFZ/KUNzNbnOz2GmRXwzTlZRTMoFYDXZfiljB7VVGTNbWpc7VpfhYkpVa2At7Rx5hWXwt9kCbFaC3SuwUYeQs9/oA1E8fdAbLe0Z/LDWrg5Tbgzy+KzdvmF40u0aelFjXLAkWTlt4PkxPRkcWiMIedI6aLM5ER5HAWozs28TV4LjxeHg9BNAExHo04D7Q3d7k8ZKt/burNcmNTQQQvhYLbVsCOz4I9swZjAGOwNpveApVQ7CTzqbETHV0Vrbmr6aHZSgZNA27UPs6jcSt9L4C+4k/nipNFhG0GvsoOeXXsZzrc3LlivG6KFPFegCEOY8TFfmTCMu410Z3cxQdU2w46tI/sLw3AVXbszXo7DU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
