travis:
  secure:
    BINSTAR_TOKEN: rqRVnVidWYuLGrOH8eynz7ATNEHE8dZYZy5n4NYkDqnBuwT28dP0eeTzngxY75YV2wx5rhAD9ZNuu9zwgpUjSsywAbUnh1G/g1eTpHqYD/xAQqOT9GDJ+FSvZ0unKXGFogNROR/1RkvJ1k/jLphpNXUS9RKCIPglNsjBUm/wUWUSmQ1Cv+hqJNqCU+qPjIFJmdOP78WRm4PSlVW6Iiu2duf25seYrVzftkEHwf1qfZUyCDJ0QQ5eIKkO1svWIyqyRtncotrD6+DLHc7bViPycdkn/4vVTVzCnk9Ugva49tI4Ak2EpDwfirf3axGWomLN5evf6gyW0syi8XsjgkG+t7EEB6W5N9MKj+ALsRa4hQ1OYiIwDlQb0Ry7tEEjNXzG/HF+lqY3DRiigsiqVP4FYRKzKPE6PJNr/DK0RI8pckz8gI6urmXcwRufFq2tTHDKgR9uacdltmFSyYpyqQoGh4i+FR7znYGH4rBcYl5TJ4rxYIS+/c18EpfvCC3cUsxv0uTA88re4zQD3Zj6cw1ZfaOfN/AD+VJCBRnFYCahmBEnxpinuByiAYo9ZcW+r5v9krpn0uQ/ufLAUCSUWMSFfsnSBS2iBbT34A3+A55YBrhE1I5PYfDH80N16/bmjzS+2M20aUapuOc5ISbIMAZ6p0ak8HECK86iMMUGggEpMZo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
