travis:
  secure:
    BINSTAR_TOKEN: kJU8MQ7njwA+8ZFxN8jOwHGgz28legEIKUf4HZxduORffzfd1K9nGqJ6lezRZ7KqUorxnAK5nlVY0bv7FkIevomCbDhyQQimDITcwHoExF4cFRCK1VdMTw8PP/2/FRkhVGWQM9bjkKbLpufdRoHfslfVPl0JI7NmAzZCvB8fAxqdw9U2JNawiuoZxwiEsty5UEPugycmfXMR54n2tmdH6Y5uysKJkLYJUx+bSKttLna3JpHNKWS0exwYOshJTqvu2D4mfuFbdBWgHL3nK8Y6MU1AAzwgo5/ldMJL44w3bVYRUz0u3Xo/7/TvNjIJT3zmRCpl3JgHHBu/mMFNmwLYEa/aql4uoFxqIPnlw6hrRTOCIHnzRSoBOvCAnUA6gWjTRbVVBQX6W1sxFWldDozSJrFORhnlvDivQh5jC3sBjleBfxoQ62XGhTQabEKp5N7ENCqXRyTz9ZeAkBO+RB+qLvAs56Ik63ArIkzQr2m0ANJauf/9O3RfIUazdSi7Xuy7n/9gc22ku7VeNRA/b1p36r29S2xWj/GGjxLeFHj9r1dEhxbCcSIhvAnULuC8NmA4OYM87Z2gkUvz+9mhOG7n13P7/RLXOUyNAcBYukxYdFEsYFNUvURmDDIRtS6PKkI/KVkB767Xcgu+yN1KV3C12by0fJFux2bDGXQ6YGSg4/M=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
