travis:
  secure:
    BINSTAR_TOKEN: LKjOQc8DOrIFpG7bnzF0Ts0QTvCeV78qGDDP0ldQ1goLqvZApUk6HB0nMKI1GpskJ/8slRNX0IyURRNVLeRcHDG+vqqtH3a8zpmPD3/4vXmyeeqQNqe6nEhyEMBYa5+BaJ3wh3UEmgygqB/dRr9l0/8kheO0z8HdF4R2J160p0wdpkaSyceQ1cG8vKWtY6sFxib475OUtRgEhL81PTKbiZpm9YeX2kcEhK9KXNGrJ1muxxai5/q/MFkxAtloPzFWz3J350KODT9ifC4zEaFb+Yg1WGV6WKaVG6JFVdDnhZIWA+5cX75vDmZiT3fRSwASpedJzrmzuHUSirH6Vx3VrAro4/S+tgMr8JmlpLqekVPpxraGU7LWc/c9rR3ue9O86pq/Gz/EWeVYuwPtgT3qrfqOPyEXB18fDZmTELGUmIusl/SlDRJLlkDyi6ieuUrUzZ9cMp15wYX2y0KNG12eZEbi0Jb18hExvSSZK+63ubf2aK6jfnPjRntpMm+UbsZSSmuxNEub0rPNQy/B1F9/ChUTCewo57roag3I/PsVKU+MI/xKhX3MTwyROg2ptWHpZ2oF2mGw923sUIKQCseFCUNxZHfEkUuX3tnXcIe+jJvREuFewNYdIUp4SsKVq6i8LZCs/lbIJ8B+uo2QCUlumd4c9Q9uYlxDCf6Su9u34Gw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
