travis:
  secure:
    BINSTAR_TOKEN: gmt5d9/avz8Uv6ooCUbCzpyWouLCvugPQn5VMA93UWqIq3qvaqXeNKr0PedTXMaH9dhkZ07MWd5Z+BhEV4TE8C/DyFTbO7uUOipp2VaF5WxCdO1pQbhHoub1a2AAqoHXG0Be9kaVO/iv8qNrh7LcXgx7bnHMjHvFEil01FydDNQRBVKDdKmTVv0PhRDgd6idJuFbGhObvKu7nikHBiSxy/C2TFlNMdJ5YUYlR63bB5hIu8pGj5o/mCKrLL564vbs76Z7v9ldoMNs9xbmxFqIn+9IisT82g/Hc1UBbqwOzo0tf5IZqL+TzJBKV8G0A6cPCcow6oZjHIx3htPXIUvOE7z7VjyqZcxuDO0hO1NS/WrHDeHjfTEkPPqH1eJAvtHl/W7H3R+DFTzH0UKjNdSIyp2nGjjCRAM1a1C/+wS65U4RbLJw/i9LJvB+73lhrMJL5ZuJk3wBUX1ZYG0lxcbjgAkJmiaYtSQm6GCUIeFFC/e7FH4b9IJY8U/Ak9p0it8bz7bXQEXyK0qZC8xVVrG0/sTLsMxYN6v44acIKnOxXo+CIzKhubQhsajhN8NnneaIg+zlV1ykdjS3uNLg+gk2OC1OjT+B0lnn5usqBhEnxQ3XanJ8CBUbQgVpMpOuvt3YoPcdq+807qrn9d0R6XrBDo4LeZst7Q6Y2Fy0hYHTyeQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
