travis:
  secure:
    BINSTAR_TOKEN: XY6Nr81uRt3OgkZPiIIveB48axIkx1vlQ/1Gw8dJg6uqZCLHAJJYxCM3zQ316dG41S805WLJ2YU8gvwRpM+Auh4FIbee/+Iofz3GPcJ3cUk8sFad9bIXyCs56he0jwQFcY/8JDhiGdnWvDtOUy7xZDI6gAIUIviNfxlo8lcPHL7T9PvgUynq/0wrHJnWDvDhdrChCFyOBoNhsAzjhwXsmj11LL8VyRTeCAY8YZn6k4l4PQ1Jdjns/NT53eaEWJ6CkUxw3/a1c5A3GfNuM3DYPuRC6xkMMdGiG3ybQBObhUbma7KpJ4FGmvABzIdMpYiGrzsgv2CNI2ABOXXBQzOY16fWKOD4/P2Eejj2xFZQ7qOszhqZI3UHKO5dUk7q/yz4RUM+dA1O3kxH0raZTFEnMnn+dVbm03WVtqTLvbE9u1RnwOigcLZlKLUlyU+blOM7Q5zG0A90mqlqEdFrULOh2McF8WfbF5gcWaJS4iuVirdcyU57CqX0LBHEhrralPEPPuoURVALd7X35XLLcyEl5R7w408rlK8eI4NgShCNZx+CYVB5hujH6JlWefPzI1uh7NLaU6KicJR7EX8/1A8AhiFaTsS22aSFm/m1xBfh2s7Io05nXtTcfNf3fF+tkNaKyTVS7cL48E5SRr/+BFeJzIpgU/e97pMpiHuqOqqd9i0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
