travis:
  secure:
    BINSTAR_TOKEN: zidLfthcIxIbsjM/eBLbfKOHmEDKiCCzmdCb3/7uNscZGrHnn50//bkCttfEbeL13BeZp9QS1f66g0Icb16SCIZbgPKn4IlmDlbTdPW20RZ2XjxK69SePvMHhY27Fve8p/10gUdAFnlY3NvYlzkcTdB/UY/StGxw8iPjMfd98VWZ/RslGnKjf65mD2lATLhYA632fqVCPtM0qHTDCqGpEmGnBWzdanEstkNsNcSY0F9XFnrp8OegVNu/3QRBglgCiMAHGfHcOx01eFkQ9bFRzTI0zCoXi/8kpFkLS/ecuRCGFI9Kfhmzuyt9cFifXrJ8/fKIFYVFuZgaycGuyo73pJO2goC3Xj+a/TgImNb6SoU6gUG7/+hgxOqHe37GfxNs7vV3PEdXaF47YyiYUIm7RSqEfGaa0bQVqdrHkSRp6/V0pvhnj3EbBYNYyez8tUC424yFnmcLjHJzIgjrF7HjcI8mh977Ws63d0X9brJHtFmt1cCgdfRVtfkxbCesj/dAaf5S6ZT0U0h0FLNVomyKtmn7eV5JHZaLcb7VvUVauBh+ZjTJYIHExw7KpP9TTq+VzPSbNssDzp9HtMnMdNcGTs/4iKrLxS3qYEEUb8MTH3/VGEH1lEsH1+lvLSTwkfdoWs5OsvKxvwmbYc9n0vTCC1Goz5A1APTmJWKBTL0MpE0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
