{% set version = "1.3.6" %}

package:
  name: libvorbis
  version: "1.3.6"

source:
  url: http://downloads.xiph.org/releases/vorbis/libvorbis-{{ version }}.tar.gz
  fn: libvorbis-{{ version }}.tar.gz
  md5: d3190649b26572d44cd1e4f553943b31


build:
  number: 0
  skip: true         # [win]

requirements:
  build:
    - toolchain3-rpi3
    - perl
    - yasm

extra:
  recipe-maintainers:
    - gaiar
