{% set name="openssl" %}
{% set version="1.0.2o" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: http://www.openssl.org/source/{{ name }}-{{ version }}.tar.gz
  sha256: ec3f5c9714ba0fd45cb4e087301eb1336c317e0d20b575a125050470e8089e4d

build:
  skip: True  # [win and py36]
  number: 0
  no_link: lib/libcrypto.so.1.0.0        # [linux]
  no_link: lib/libcrypto.1.0.0.dylib     # [osx]
  detect_binary_files_with_prefix: True  # [unix]
  has_prefix_files:                      # [unix]
    - bin/c_rehash                       # [unix]
    - include/openssl/opensslconf.h      # [unix]
    - lib/pkgconfig/libcrypto.pc         # [unix]
    - lib/pkgconfig/libssl.pc            # [unix]
    - lib/pkgconfig/openssl.pc           # [unix]
  features:
    - vc9     # [win and py27]
    - vc14    # [win and py35]
    - vc14    # [win and py36]


requirements:
  build:
    # for feature activation
    - python             # [win]
    # required for win32: https://wiki.openssl.org/index.php/Compilation_and_Installation#Windows
    - nasm               # [win32]
    - perl
  run:
    - ca-certificates

test:
  requires:
    - python   2.7.*   # [py27]
    - python   3.5.*   # [py35]
    - python   3.6.*   # [py36]
  imports:
    - ssl
  commands:
    - copy NUL checksum.txt        # [win]
    - touch checksum.txt           # [unix]
    - openssl sha256 checksum.txt

about:
  home: http://www.openssl.org/
  license_file: LICENSE
  license: OpenSSL
  license_family: Apache
  summary: OpenSSL is an open-source implementation of the SSL and TLS protocols
  dev_url: https://github.com/openssl/openssl
  doc_url: https://www.openssl.org/docs/man1.0.2/

extra:
  recipe-maintainers:
    - jakirkham
    - jjhelmus
    - msarahan
    - ocefpaf
    - pelson
