travis:
  secure:
    BINSTAR_TOKEN: is4J8UNqeiLIWwTqQeMoq4gi3Rq3NWCbUBlCzKIsF+bQIL4iOmHUyoTZpR4hT2TRhFWuLWao8wElz7wS6DTV79AizcX+LRGae+ZriOHCc1Igm5+O73HyD1mxiFdzZqnc7BBylysPqCcp36nZRoqhH/FJ3HbVhKIXP71EAqxwviHS1xJLSp6H+JWbEMGo7KWthWEBMORIsiHW22DlPyqu3xFOJmPW/IQQXlgyNEkEOsZeFVmjkoathT3mMzMpa46iQJXRtVFFLDGaZXGArGcJsZO/fgQ5fiX7Clb77Toy+OZ0UD6E+RN3Jiqj0Mww/M9i5iF1wRcVp9y9Biah8mFDycdYqIA5L/cqaKNjpC23xOzZz1AkiYM9Wja+eD8Ha76WH0Ook0iwvYS8D+UQcOkg6rTcVRBGvkB6w8TM3ZiZAF6vUA+PHUsBcXMSDqMoLdhZF5/RYi67oDR2noUY1Vl1gNjuS8RdjQqz70vG+VE8s9for4vTGY2Mw0Bjetfy+sBJNC36LsrESJ9Zr3GO8FD8TOy2YOqtoWrmBc7T2U2S9u1qItsYRKQd9FQ97eie6pKiyyl1Aw7/xt4LLweMFLfTr999sH7gu4tK5vKfL7ZXaL7Hqd6HP5p928YkthEvbJBmh+8tc29f5v2pIDpUCI6IP17qbnc1dyBopnHecYTkBTM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
