# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PERL=5.20.3.1
    - CONDA_PERL=5.22.0.1
    - CONDA_PERL=5.22.2.1
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "g1QpmtAagmIq0JcREYXlNYcc6ODXdZyGGEwf8egDExhuya1p6vHQ/7He8b69d+epaItZXo+8G0vt1lxa9c9BGlTgwY2cZLtsJIrQWA5evDipgWNpcknXSxFmij/z69NQoUvzmUH5RS5SHdgn6/FgolfMyrWJDCDTqaCxuRxw1+V1FJ0OmX8/YzM+ngV2w+ndJ2pL7eq1O8IBMlLTX8DGlq56HXVD5m6M5FMuYBzcvjJh0J0DIwW4KRtdktshYZhxb79RX87wuRhkl01vFAL7Ra/miESTIy6l9L4gX9nBK9gNQudaJIyn8qjVnTRUCzYwWGrtX541WiCGu67c/14zr4MwrvvLL0pCYF1g25E83wltsmYkIrSvaUzUBv0jH5d7geBl6uLXDObaaZqsl4M7mgu7iT2vkF/I1SZbnar7SEbzPMBxMCO/fG70/rz+Zbfj8nz7RgNeGkfx5NMMokWtIbGspICv4hpJxM05Jyl5YMHqMH2nvFSYmn1FLYHLQ6CFFAQN/uTfOaYZPL+V1UPymb+L4g2n/dRouPPtPtyskYz+6H8wBXn0wEcmeR0b1iyKmhQQYKiOl8tkbKeBHMVm2ZHvbrjtw3Bk7s+YlgDc6CL9KS7uZ9WPdk8jDKqgMlnZZ/7J5Z/c4zXo9l99UWnCEPJQ7Pca6nceO+/pF6U2lMs="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
