travis:
  secure:
    BINSTAR_TOKEN: g1QpmtAagmIq0JcREYXlNYcc6ODXdZyGGEwf8egDExhuya1p6vHQ/7He8b69d+epaItZXo+8G0vt1lxa9c9BGlTgwY2cZLtsJIrQWA5evDipgWNpcknXSxFmij/z69NQoUvzmUH5RS5SHdgn6/FgolfMyrWJDCDTqaCxuRxw1+V1FJ0OmX8/YzM+ngV2w+ndJ2pL7eq1O8IBMlLTX8DGlq56HXVD5m6M5FMuYBzcvjJh0J0DIwW4KRtdktshYZhxb79RX87wuRhkl01vFAL7Ra/miESTIy6l9L4gX9nBK9gNQudaJIyn8qjVnTRUCzYwWGrtX541WiCGu67c/14zr4MwrvvLL0pCYF1g25E83wltsmYkIrSvaUzUBv0jH5d7geBl6uLXDObaaZqsl4M7mgu7iT2vkF/I1SZbnar7SEbzPMBxMCO/fG70/rz+Zbfj8nz7RgNeGkfx5NMMokWtIbGspICv4hpJxM05Jyl5YMHqMH2nvFSYmn1FLYHLQ6CFFAQN/uTfOaYZPL+V1UPymb+L4g2n/dRouPPtPtyskYz+6H8wBXn0wEcmeR0b1iyKmhQQYKiOl8tkbKeBHMVm2ZHvbrjtw3Bk7s+YlgDc6CL9KS7uZ9WPdk8jDKqgMlnZZ/7J5Z/c4zXo9l99UWnCEPJQ7Pca6nceO+/pF6U2lMs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
