travis:
  secure:
    BINSTAR_TOKEN: onfU6x3urVyAhurn4kyGhZNjgfyrCx/bOIy4do794ArRefSqRQRgKtyAv1aFiRMVWZgG6z+YZZHtDsb1T5IQDbIVozlVCascjwXfxV65ZBnrqJgMA1/4s4d/LCbeV4Uw23ZVzXrXC3MjjpK4l5uWB6qQj+K5J5AJ3vuAKUZzRImX8fWkClCfaTCgXIM/lFYMwSAVk+fM/oHJSN2aRwX2tZMyZswqpj2zGsIpJmCqKb0akfq76miWV3+u5Rf5K13olwB7G7MslvpzvRO6WZhObV42Wz2sDVeZyYLyKaVz/drqIVpLXESE1kwbF5gQ7XUheGJMGijaw9mRBn/vmITcLu+j1l7mcMyNMwe1/ls3n4bI1ofTIFO/jOTX6snoyNP9Q6x65+YH+FaJOZhqdIPVq9QO0vQAGWsVkyG55xILqi6oMRMY3rYfNuM1fcFIfIc6DScRJfHVvKQ8SrYGPu8l3f0ezfZHzjNG4BV6pPpzaI4aj5b/rjQh2dG9aItrmw9pmvpvdcmwpCx3MWWn8lH57NO8AuSs+lS7V80bAuXx/5by/O0qu7aL8Zy/891j1DiDQG1UclAmRWuKo55Fe0VHsoX1UXuZBT88kp4hv5aXWFBdkt2I1p4aC7GxD1aa7R4PzTguoDjYu3jOF/xOkFf9PJVf3AAMBo8rlmJjebe2Zrw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
