travis:
  secure:
    BINSTAR_TOKEN: ZYTlXOn+1x76Q6OcB9LmHZOfozZc5MXUPYIeeJNszHjTMuY24hszOXf+b0eigIiHBdqlff09sf1BNwkR7KeU9AcXiamQJ862D8s0bDN8GnAgVihbGGAX22kd7+i4GOVCvTUivvohkykMTo0Ymg8BKNhHl6sEAycfMZjmxizoocbB/I59LxSspUE956ou/BvZp1i1ZcHkuzpi1eNrvgaqiSOoPhG8LPXLez4UndpGaise73sA5QiVdxquYt+YE3/OmD5N5jPQdboi16T/ezm9UH03nwD9YZnsXsJn/1sPN7gNnMwY93d8m7H+o0L9oDoUnnQEE3DLDt3d3FiABkK3yubwhoiUW1RNIthZzKQ+tQhrjfv6kDGfcXnVx5tdKGSjYYXBhCzI6fj5HlNYzU86SL59Bk0jAWSt7Gyx6XgyzzfSzasVcICo471QTj+CB7xAjdR5UQVuczCvUO+ILroI3+DH1mMIyXyKAArNaY0dg9r0cmX7btJTDaQ7tTmAeAMPBDh7tpKgpwBq9FoznVKiikJL4z71P60X3W29agZPF+1hiLTtLTAwSQeMQd4FiRrVmgFiAXQ2ibao490G7HTwaVaPGA3IrNNjYFd9qfx6zSxwXKJ+k6FIx8ibH0LxQxcFvHq3pmlZSPOlDXPLX1fi23OmOkRYS8F4JKS25gV25L8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
