matrix:
- [[BLAS_VARIANT, openblas]]
- [[BLAS_VARIANT, noblas]]
- [[BLAS_VARIANT, mkl]]
travis:
  secure:
    BINSTAR_TOKEN: 1Idrx6ALL2kJ0JTAr8rInIovviwuFKDlCgseuY4nFqYiTzBvIKPM1im7DaWmhW0+ZZirj7nt/bBZAQcFwfc8I7WSqrFCobiSUnpnHdsT2FSRpzPDE5SmOLck+RQokTBxkjmkJBgpNXMGnvhkTv96dbfCNUWkG/EFQcZvry0fm9M8aio0WzeVZO7VnDIDRX/6r4G4vn1ca4YL7Us8zUuV9Adnz/c5XeZCqUBdWCYgUMhQzEHJPNwWK2y1TCrg1cq0/BADCvoUGtykfv59LFPdmGqS9ixFwqLe2sCJCmJs6W20JVB4T1QmwAH42RJ4lcV1cyPbQ5dc0pinKR/5cxQqYbJgMK75Gc971d1baVgARkVULDXRVsjBltaCBHubdw7j+zJdXhG7F1pZ1AZjLBbU58NLx+5axyiE1WDYPnysByPbBIa+Y/u9sW9czdgDfgu7VWT+FglImctcNwRrDc+UuRgls/hMecEYGXljyTS/OxSOX3mH8o6mDTjG0B2X+7OT/W03dYI+036qLcgQmH0J3HWIJ6oeXPCgCmY7W7gmfbt8u7ZzjxxGOjw+CXO2JMA7hA78vEmYa2RQ16CW51i15mTlgQ1iUFVZUFHT+q8CEnv8QI5RwZz4sl6pe2Ebp89t6qD+5GtBLtutWkNeMERpEaZ4/QFJ2iPKP4Z+pioTzDs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
