{% set name = "wiringpi" %}
{% set version = "2.44.5" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "0031568b312ff321967ff274df06784fc336750f42b2bb6fbbf9b48a51ba5633" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python
    - setuptools
  run:
    - python

about:
  home: The package home page
  license: LGPL
  license_family: LGPL
  license_file: ''
  summary: Summary of the package
  description: "Note\n~~~~\n\nThis is an unofficial port of Gordon's WiringPi library. Please do not\nemail Gordon if you have issues, he will not be able to help.\n\nFor support, comments, questions, etc\
    \ please join the WiringPi Discord\nchannel: https://discord.gg/SM4WUVG\n\nWiringPi for Python\n===================\n\nWiringPi: An implementation of most of the Arduino Wiring functions for\nthe Raspberry\
    \ Pi.\n\nWiringPi implements new functions for managing IO expanders.\n\nQuick Install\n=============\n\n``pip install wiringpi``\n\nUsage\n=====\n\n.. code:: python\n\n    import wiringpi\n\n    #\
    \ One of the following MUST be called before using IO functions:\n    wiringpi.wiringPiSetup()      # For sequential pin numbering\n    # OR\n    wiringpi.wiringPiSetupSys()   # For /sys/class/gpio\
    \ with GPIO pin numbering\n    # OR\n    wiringpi.wiringPiSetupGpio()  # For GPIO pin numbering\n\n**General IO:**\n\n.. code:: python\n\n    wiringpi.pinMode(6, 1)       # Set pin 6 to 1 ( OUTPUT )\n\
    \    wiringpi.digitalWrite(6, 1)  # Write 1 ( HIGH ) to pin 6\n    wiringpi.digitalRead(6)      # Read pin 6\n\n**Setting up a peripheral:**\n\nWiringPi supports expanding your range of available \"\
    pins\" by setting up\na port expander. The implementation details of your port expander will\nbe handled transparently, and you can write to the additional pins\n(starting from PIN\\_OFFSET >= 64) as\
    \ if they were normal pins on the Pi.\n\n.. code:: python\n\n    wiringpi.mcp23017Setup(PIN_OFFSET, I2C_ADDR)\n\nThis example was tested on a quick2wire board with one digital IO\nexpansion board connected\
    \ via I2C:\n\n.. code:: python\n\n    wiringpi.mcp23017Setup(65, 0x20)\n    wiringpi.pinMode(65, 1)\n    wiringpi.digitalWrite(65, 1)\n\n**Soft Tone:**\n\nHook a speaker up to your Pi and generate music\
    \ with softTone. Also\nuseful for generating frequencies for other uses such as modulating A/C.\n\n.. code:: python\n\n    wiringpi.softToneCreate(PIN)\n    wiringpi.softToneWrite(PIN, FREQUENCY)\n\n\
    **Bit shifting:**\n\n.. code:: python\n\n    wiringpi.shiftOut(1, 2, 0, 123)  # Shift out 123 (b1110110, byte 0-255) to data pin 1, clock pin 2\n\n**Serial:**\n\n.. code:: python\n\n    serial = wiringpi.serialOpen('/dev/ttyAMA0',\
    \ 9600)  # Requires device/baud and returns an ID\n    wiringpi.serialPuts(serial, \"hello\")\n    wiringpi.serialClose(serial)  # Pass in ID\n\n**SPI:**\n\nThe ``wiringPiSPIDataRW()`` function needs\
    \ to be passed a ``bytes``\nobject in Python 3. In Python 2, it takes a string. The following should\nwork in either Python 2 or 3:\n\n.. code:: python\n\n    wiringpi.wiringPiSPISetup(channel, speed)\n\
    \    buf = bytes([your data here])\n    retlen, retdata = wiringpi.wiringPiSPIDataRW(0, buf)\n\nNow, ``retlen`` will contain the number of bytes received/read by the\ncall. ``retdata`` will contain\
    \ the data itself, and in Python 3, ``buf``\nwill have been modified to contain it as well (that won't happen in\nPython 2, because then ``buf`` is a string, and strings are immutable).\n\n**Full details\
    \ of the API at:** http://www.wiringpi.com\n\nManual Build\n============\n\nGet/setup repo\n--------------\n\n.. code:: bash\n\n    git clone --recursive https://github.com/WiringPi/WiringPi-Python.git\n\
    \    cd WiringPi-Python\n\nDon't forget the ``--recursive``; it is required to also pull in the\nWiringPi C code from its own repository.\n\nPrerequisites\n-------------\n\nTo rebuild the bindings you\
    \ **must** first have installed ``swig``,\n``python-dev``, and ``python-setuptools`` (or their ``python3-``\nequivalents). WiringPi should also be installed system-wide for access\nto the ``gpio`` tool.\n\
    \n.. code:: bash\n\n    sudo apt-get install python-dev python-setuptools swig wiringpi\n\nBuild & install with\n--------------------\n\n``sudo python setup.py install``\n\nOr Python 3:\n\n``sudo python3\
    \ setup.py install``\n\n\n\n"
  doc_url: ''
  dev_url: ''

extra:
  recipe-maintainers: ''
