travis:
  secure:
    BINSTAR_TOKEN: rdOnNBe5WwcxIYNhTdMsNYvjmEWPwQSoM/F+a1rvPRU22fKz1YxNaWNrKiu4XZPSafGlIFXrWa61IA31lletdWEzlMhdlErpNIl9ID/AcS0PChkaRlbEB0YESxPdjHWHps53aYhf2AHYhQB8YBkFGNSuv7DK4/TGuNZX7nM4SpUy29WfUOzoyt0MtrnLVRajdKSdI7ktbtQm1h6Mq3/F1JT1GPQwfq3fx43uN9bLBFfGQ8eMx0KS22XNesuaXjFNt46SSPbv8uyajkhN2n/9LkKfyTTtWKobVN6sXwor044Cd9tdSsVEfAjsNhpjQl1WgWOKYhfge9bqs0WDZGwV115pJe9r6XTT9pR+18wxxSGljNDz6uX/PgQiIr7FzGn/lDsxswSHcuKw1gKnzWso8ak9AFdvQNNDQplHvFa0VC7QPttEIjKMombft1Wy2xI6jHdvWITRCR3TKH4remlyoN2S4Q4ryFsZb4lteJfXD2038k6zh1HljhdGI1bIL6e9QMfcCHFo10HBKzCYvtkRibXVlLLyZoQIoDFMYIMJitrSVEmce4W4zoy3+EPBDdFfvylUB1bWtX0LK7JYGWRGxwHu+rPYmZNn5uDe3y76Hb/x3qIsI1YJ/qBUNOPpIP/YDy/KWkHMUS3R+2H3hdO+MJQVd55S6H6rp5Rlz8gt/5c=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
