{% set version = "0.14.0" %}

package:
  name: libass
  version: "0.14.0"

source:
  git_url: https://github.com/libass/libass.git
  git_rev: {{ version }}

build:
  number: 0
  skip: true         # [win]

requirements:
  build:
    - toolchain3-rpi3
    - pkg-config
    - perl
    - nasm

extra:
  recipe-maintainers:
    - gaiar
