# This is legacy recipe, which has not been tested using conda-build.
# See: https://github.com/ContinuumIO/anaconda-recipes/blob/master/LEGACY.md

package:
  name: ecdsa
  version: 0.13

source:
  fn: ecdsa-0.13.tar.gz
  url: https://pypi.python.org/packages/source/e/ecdsa/ecdsa-0.13.tar.gz
  md5: 1f60eda9cb5c46722856db41a3ae6670

requirements:
  build:
    - python
  run:
    - python

test:
  imports:
    - ecdsa

about:
  home: http://github.com/warner/python-ecdsa
  license: MIT
  license_file: LICENSE
  summary: ECDSA cryptographic signature library (pure Python)
  description: |
    With ECDSA cryptographic signature library, you can quickly create keypairs
    (signing key and verifying key), sign messages, and verify the signatures.
    The keys and signatures are very short, making them easy to handle and
    incorporate into other protocols.
  doc_url: https://pypi.python.org/pypi/ecdsa
  doc_source_url: https://github.com/warner/python-ecdsa/blob/master/README.md
  dev_url: https://github.com/warner/python-ecdsa
