travis:
  secure:
    BINSTAR_TOKEN: fVWVLFg+2tm+bnX4YX4jiTuAAIjw9EKhl5bamChJzzUj6D4EPtQvrP1BkckpIjIfcpZGeV7q9R//1wiMG09CR54XJQozfQxCUEQlHZtvkQUii4xOqzU/hg3oZeZlr6T236WOrU0xHTm13C1SC8qB6wGz1UX7602W7uH+LTDD/EurmPG7C59zh2Ii/laetLM81mHU1p6bXk88xPr/wRlfhZMtw72VPyxSGX8O41CHhGXoyt7sOoT/ljhGxuKJM6M82epouJLwGUL0ys/b6XebqQSkIJ5gL+fpTfJw2VSEE65L7rdA5xCcx0QAx5gEVr3YXzOMQURfG19S3N/28w0lJPANPdl3TJN4/BZ8e4RBKMGld287L8/DJcoyd2KoSvfuemlTmLHNZGDDUUn6P4BwixoRhL76kWnXzhsiSOfihx+9b61FlcpJlhKxGTMqbB7n7NZxzpIuqUo1gkJHUUVRmB4PeDWCL4uCbZ25uzyHhswDBYjOUbmbSq1M89C7Sg3dfQ8Fvt+jfKFa2YaVPCKdOW7QN4PODo+cKnfjmbg/I7e3J4fLEqM7vZhDUjW0LEgj5svTXdlCzK8JgFgjthyOHE6jV8i8WSW+YK3Iuh+k4+c67+qOnO1srynEstkkGkn/4RUbZ/gyHu4mcQoPslBArqun7XngS2Khcb69jmZdsbk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
