travis:
  secure:
    BINSTAR_TOKEN: ez+S6buKEzv76TW3uzyMxPiulPiQMhCcQbnus3hOqKjKKuHzNt4UMY1z4839rbwwcaFtTRLe5EPDiYN11uaZcG1fj7DyPSv3WoDqHfLMBaAsFSGMsG2YhaWFJbHNBLNqa4pWX2d2BPiMV5YJzA8gy5lTwPREaIXXKhv+K8kLsIO2kAeJUkvG5e4de3VjfS01wfd71N5/baNmAWNpUZg+kPV+RV0umwJYC92/1ELaQ48OiCQhIND0NN2ej7RTPFNdacLNcWXFgycPuCCxLzExzbb20M0q9lFpGkMxFZIH4U5BQiTzXaz6Ntjf9or6y/OzQQLBWqN36eMMpXRV47E+aAJ8FCtsctDMap3SnGwfx+WRejvXB7AEnukXVkFWtHOiVi3NXf2OORZLBhn4Nta/v+X+YvDmIP+ljOP1QnLmXfVV/Zxv86wRL36B31DBqi0jlZ7b0BZOXSVKYbFG3zk/WeqoAQTmU4zCwrQnsQgc1eE5nE+f6cujOPn1VACQDggaaRqaCGwSG0mzNlF8GYHgS/+o0uChAJuC1ZDsh+lB/Gvm8i1jwdF8yZGoR99cXWBFnCmVz2yWEN+A2X28T1q9jsTBgfiEyhPm82DaWm1Xu0HZo4zHREWbK9NzMM8RkdPjlhE0hqidbeyDz36aE+JFfVQN7CQDWIUWzne2tfZK4qk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
