travis:
  secure:
    BINSTAR_TOKEN: aqeDBYTdG/IBnAKiJlodjTB4TNl3K5d8PUzJWOu4Sy4qEYn7w3i2LcoEVGQo2E189OEd8Uw6wr/vdTC/iGJtvDl5gIB4yXa+fkRyLVk1E+x9a8sVpqsbPQZ+PNN5tO6ycAhL87nhEm2ddDkrkmZYDUnrUuUWZ8nGRRS99OMj+7xVnYRrK8nhXANG1J+0o407t91idS95ym93bPs5zcU+J+CfAP+4VNwk8uMRx3tNfObD268u1VU7SvGEDtluC7LPGTUP2u1cLEvWJ1umcuGOR5FXyoRlzbBE0FPusyTgHjw7n+H2geS6DdUW4kp0EFSUgaQX13628hHjes2dqR6/TfnLvTvAvsLinSY7we2gEamUi9Qh8t6y9+6cPGiwcx66il+qOTCPrSinjkvAyrwI3KIZstxtZkuilmwXxNx1U1My2ArQ5mh2Sxv2Y5eGIgM4jBRaUo5jAy9qQVgpQe5rpVO6IhVnWmFbRrlJA71uJ+K7c6DuV0/gwECtxDIKZhBPfn7qpAu8sOyTT7etMuBlb3l9gRWekZRhTXhkAv5G1uT0jjnEDqay2R7pkkng+8c5n9/8EzmFLR1Dce37OXJukQyOcfrz3Gfy3QNZiuyCAzgAGViKPj0x0yw0VhO2ZaHQ0rSVGB4kp5VixvynwL82mi4mlQrcX6ndZO0D9Q4b55U=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
