travis:
  secure:
    BINSTAR_TOKEN: R0jTdGDdLNJ5vQkjM3+D2LiOhNI1P/upPXCo3KPWiRq3sBPT5+uz9+KoUoZWO4yQ89kob4oc/znB6dHns54oZM7UcvrpWgoTcVko10csf+KQT2zqBX3HBoT0qbFHPaUVXxMCWW2eN25LgQ9j3PZyW/eHMVGv4FIyX06fhlZ/draLuK2+E+oEWl26l1f7MAs03yTa0FL0OYlQUiGAZxJO1kAwpv+r+p74pduo/pbXH8V5MVUV96gY1MDr6zLtWklT5Ktmd81SdOTRkYn53hnRuF6H0TQBgisGDxQtTpDDjDOzdOgLtcsKUgNjMc4mFU6tW9TitSnE0dBXP2OEorRq8vVdTQ8ddzrzI4EptgKZSglNHEdfkjUfish0YVCD17PmuY77NSZK8Vh4z2RYFOe14E/74QEiukXSlDlZvfbm4tt42Tz/1ZkA1kIcKsMnaMoWZutP1iOiU3PLm5GGqmUCBYGSa/YZBOzU7Wwu46CyRCzBdQ2kXkUFTrezHUbqS80nRQ9Mmr4Isvtp56uJPmv2X+cvixCwCzhxbEyOPXe8McqLkbXIp6ymK9FYwZzhq2Qb0YEKL/NGCUB0BMmMm5BZOJcZHgtSe5kATnOfnxg9fXfb2ixGQPhdgdPe5iFDZly0VmhQtfJH9WmwhEGPlfnDoO4LvAY/VN4GwntIZhuBupA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
