travis:
  secure:
    BINSTAR_TOKEN: rgjBfhsEf4nnsgtb6D4eLTwk0zBWMGzcx00ZJ490Mz5lpNvRhZ14DhWsP9d7bye98NWCxFLaXY6h3Yuo2uQzpOrdJmVSNCYj5ehZAvf82KHPclf0J76zr8LpPuMGT4gAxD0kAGuFNITYjKeGQFKP4daTu9s0jFPl2xsJFGJoFA3h5m0vnFLEbDq3XdYrk+2/I0TRdVv+zY1FkECOqjlyC7EoQCCqrcva/nvrfauTuPCUxDltoWsW0GCC7Exkdr1zTmNZNTtO69Rn64iKCOStRG0c3lOoDG+URpSVeXIICdUQi17cN1mjLYpGkJZjm8GlrC6PzjLwmKBhxSBjS3jbvgh8pkIFw1fBxXSPgFGYCbc0XlcdqRf8+9cwY/j8Zydu83GsJpvkm1GRqQbprhEqyU2mxjl2eZfiSopUBqc0g4xgDRQ980rLLPEClHu818duuTVFSz8Vw/nuSVIukeU5f0GzEgdVwFe02oCe6EuU3FbuEwrBQQeVWTeGNqomc5gjKOt1uyutm6W4E3/T+JQ4QiGOSSEByQ6SynqGIZCmqKT+h7B4EcSrUcyuXGgL2G5Vbbwr37NT6wRuGaJM5UDTPbBIV7FPlwt/gwfAiJV34f8g3Inl9iA256kgfiJSuhk2VoW6QiBnTB29SXmTrMzYiuu0pPcG5wZDiXPFwITLSMc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
