travis:
  secure:
    BINSTAR_TOKEN: Fd06bSOJMK4dPRYwure/wBaqOWde57qaTKJlS6ENK7wpIDCoimPyLk58XPdTbv8i8Ihh1ArLFnL9rFPBCD+eOtp8Ax4qC28gslx95irzNjmlkveOrnQstO77kwcSSLxzjqTScQA5dAR8LDMJtiTgxMKp3T8C6tjeUet84cgEj1weI8TTF74J92PL+mQulSH0R94hc0NlJ/t66kvB14rb558lhAAOAeo/FO52vD8tiw4Juv+Aw36nY5V37+4pE9e4V0Vlb4HaWainiUYF4s5pv77V7VKOTMlV9kdzH4RslJcUjCRTOCghJC/gA7HBOLpGhIfGl5BHNHg4Souy7MWZNWDCH69MGjh5sBBDmShBvr8a5u272l0by09z1F6CyznEfJ8RAh3deA1wcIaRAIM2IeVU0nW57wpBN2Hmty1g033yxmvnWsUj78+wUvsz/tKBo2EAa0evHe+XBb+ih71WX1c258s6rw48CNmq0Svsm0jD25AZBarwNkZV9k6BNSb4Dev+1sZiirGS0SIKPXrt0+3I4s5P9KPGlNwDW7PPRtY36Mm6AZlUAPHsBtRgJxo/HXkl6IX3aBTn69eZnqjxW0Ey1b2Z/Rbws8s9VSCBV3XtRsBqq1Q2tGPusZk0FjLFs/wbULKIdLgB+FrsgQHfu9klhr1y/vd48F9SJKFjKJo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
