travis:
  secure:
    BINSTAR_TOKEN: IOg5+8EUpmaiOod5skAX/9mvwEMCkKLf0hgEJNCvLmjUBayZLw1EcdQTeDi7jBPWJx20G0doEfq8IZD6+PczQ3tfl8R/vK7rQzwK8KBiTIRnfcJRU5nWNdaooz5akObAFHnl1aW0xZuD4LMLVbWGvZDhC7ZXv1ueapWf20S+WXxC8pJzyVgSMZyNAVml2pdzOxsF9LGbl9pUZyrpsJzRc8hfau5vcv8//8fQJcdPD67TXWoNBvdhAjW48ZLi8jNPdzODsKTioP3xck1M2uzY3CSgZ2PClJaxGH9d7SkRNyG9iYofOHi1Nz62ECXvg2cYMFDlJGwRU0CshNDNJgKVHpqY4LK/LmWD5VPZs9OFGWOHw1Y2k8T01mkph7AZUpy421okMMeub0EAPjEbzedIvjszBKkvYoigrx7h+jiwLQU5BngN8Hjh7FjJRzd652pN4ABrREj8w2GfKWfZcdYccEBNFGtvXXMzLuyfpOVM03keSkU1qSGiMvXB9YPedPIot7c1Fc9m/Ca4sougcmJw01wspXL1E2sF+sH5GpuBXEfTwjuH51HB4naExxPktJ4AQbZ4fZA40JORQZTyRGJ8fZxvigSX/yeTOVCmzdW9RmmM84/W8FVYV44i86lKF5xemEfdOGFKO7hoahMzi0NfI3g27YxkcM2p1WDpTPEsRMc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
