travis:
  secure:
    BINSTAR_TOKEN: HQDhxqoja9hg3HkhuY6UhUvdR6V1XXCwWYUsQC87SwGFIHzm+yxTBKSlaZ0+7ZyhvnSckMcaUxYER9pG0jztXGQmdw5EwR2NWutgxen+/MSa7RHnE1YAbrVOP+OkXDSfw+JnQy1SDFEvYMvYOBF1typgcwzOghHWJnReOEtUVnqFhDArYIqVRNzfWFobjI+fCamalS1rD8Hd0GRauJ/xwA91adrjOCQaOcFMOcrSYZR1AgyormyVkdNeZJHaIKu5yPARj1FwEMcqxumPKOjNOELhFPm4vbvbLjwWKBmpcvAQykOx8RUWkUr8ciS/MVaiX4GoTtiOGNmo5N4jrl/lvq/vCPJ8KmQFq026g+c7Pr0StB1nlDQ93Jn2y4E8njNyraqx39Iwh3eWOE2+dgFLpKjHrlK7OS2NmxdJnceNlsxPP5OzKO+0KheVDvtepIVl0Mb7cz+MZJbxsEXmu7nuZunWAc6KZRg6SC2UrEr3v9XzpRb7LL1o4WkgH6u/XJI53fxEwtkj9ieMcdzJohR5JHoWsVtYtSDVGjKPOsA4SpA8IqxGoB50j8vsPCsnOe0TIIlZ245kLO2HiDThmPuaLXZ3GYGO6tCa/iVbbbydjxCguJhPu7Tkr4mvlTQFr+K4fidivvxYGXN0tnlr3fxEsKCLbih74RuLRzeGDcGzuA0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
