travis:
  secure:
    BINSTAR_TOKEN: coMz+Y/EzDcUji2/CoKoE1M2yos2JRd4joStc3mLUcPnKI9AHEwSBlECyTsIW8Vv6ebqsdQrb7izemb6fSjQatC/g0a7yqJh9g21OZj/csdq6CZ8SoPfBTviOg09ExyZ12aoG+kN+TYNchdQ6vshKTuweqlY4J2iVW1eX9u4/Ct3OudLxEtKIjc5OkQ5fr1Aa6TIaXDdelxg5agrcDic83GhMI/XSanEZn29vFusjbhbA64v1piCG2uSSoV2uplm4WoiSYfZXukbFwoCzKmu68kRWpHP8qIjwknJwg9h/pBXm/d6fwZGbHUuMZWYi7+WDx4cjd1Fqtt4rJmDA3yOQ7bnMAnqmm8F6myOWdUr92KrkgmztVpImCnzVM/ActiQfj9FFOcZQ4qYz1ZIA51kSTKQJZqFa5X7n5MrK2YbYDJbyWJz2vqHsZ8u5xRDCBy8iQEKu+JzMq/jPhiiRV0TdUVZZgvP+qP8tPXwqsDIevW6OJrroLJ7ThlbirQePJm4Pp2dbXKQ9irtFceA3azGYWGbANY4hygiO1LEcgtojJmaJiDbnpYyb/xXQ+HaifW1kHsdbI+jwYWkTVEf/MQmRi2OawQEvTLxUn3T674twtsRy3gnVUuG/cCrqJiQpaEhAfwCTFsqkRoFfTENcMfdpnN9zNz4hivULLIOFI9dKKs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
