travis:
  secure:
    BINSTAR_TOKEN: Uo+aVvN7bqC2+nc2uGWNej8Cat2O1aAlYmsr9bUJL7qUbktBUE4QE8DUa7PZq3HH7KOWiYgX3sUueAkktQKrSNZy26TA0ERJmOU0zonLTEfaua8cDyQEUM8YblgsPffgptSA8nQiCCSAena6xnpo1/7jzxBn6+nrCrVNuo6kcEkesZZnDv3nT6R9YqkKRlao7cAbDDcTx/la2xU90c2DUhYNnZM+iLcFKoNzwkFBO1tIzQCu5kyR2eDIY1wTT0nlkWLt3o9kvjIS8ZlRPY6hktiQXJglod97flyPUv35jsVtv/fUiGwrNdyX1uPPs8WIhyOkwkDbm2tk5+sr/G7GxxFU8tahyRQw+KdJbJxCxqPzHuBHonbeqYQgccYOAntuEHjqxUXKOC0TQUkvYECp7Oh2m9NkLTZ54S0Nd0rNFBs3WrfntZkggj70IAXxIQTzkAl9m8Q3wvCGsdeOncwrQ/r6gS84LmJXkuGOuXKkeVG8iql6s1cDdwSYyvCBP0nNEZDyYbwHKkKaP8lyIpfa7iJM22uZXeBaYjgGLZyOb7kgbjfViLNAdk7VcFjkYX2bhx534P2RwaVE2LS5UeSnwIODnzoqxLC9y1qKyd4jtJQbBWWPMD6AzDoOJ1z6cszMOKdQcDV+1Z3Vg5tGFyRSnAUMFJA140qyzEknvMz+Etc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
