travis:
  secure:
    BINSTAR_TOKEN: Y0QukSiYWgSXTTTCQj50+/jRPUvFjo6wRX5+8aRPScOCIZg9iqyjf5oCZY4UkqgTw2kxsrZ4kRcplNlPdHYVBIYbuauWMejLFNfyq20CCwZfUdmO8CC8+huEfOOj8TaN7FAyk+oTu3LHUhJ7T5z/AwBiFlysiIm0knBptqG/q3kQS5I3VrekbqF1FUVDX3g8rRIg3N6ZJiUbaBKGtPRjMX9dKBR2ga8R2/Sj0FS/A7zcQ31Ptfc6+VR/Gc8C0qdc/wecfcukEYX2CKCgvfosuE3bWC38Y75HXA2quVgurCLUg73XtA9L8jBnALvVada3spzQecqhQ8D6Jiirn+5UXPb9r7PWluN7dTF1a24UcHX4ROI61afyQMfja0vjxT4f8TkHJv4cDrWrP32CF/jwh+loagOuFUR5SpP0CiwPNXcSTEallLEjpFHWE9RwJe4NDrutd1Oq2wjtIL1L7/8sbEYrBv8A2OrvBAiofTua63dUitCESGFgBV5anfNnDa/mWYZ2hoAK0p0mgisimqGAjfwud6bQ7VPow2Sjhv8FiUgl/QUQfWiXnGy2HLUjISr8zyAWpqeZS8mGNDH62T8HZ514gXripCJHWuUWmTSN5c16eP1iRjUtOr/4bS5UCyV+rDd+1Y6XEEJ7o1pstegS59hOMWlGeyj9JNczF5BJNoI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
