matrix:
  - []
  - [[VC_VERSION, 14], [CONDA_PY, 36]]

travis:
  secure:
    BINSTAR_TOKEN: Fk5X5REPNJttDZyWNLBp39BYtA1oUj7G37/FyEXiBN9v4545nQgWe8ZuQ429Y8TPmfjW9jfvjjfHo0Sk34v2rFQqqoU38WyMsb9Jh/PErizXQcekn2GqVaJdySjSJf0Gbf0eQ62oK2he6ba3xTEWMLt5z7ja+y7NhmmzKPrY4DcHDacWBei694VFXWC71HpeVVFDl8V6thyx7nR+SCn+Ca16Hb0wZxL4BttFx0+z8cYf+qEN+2/psS2hh6KaoZ9IzjpgwUn1exPuSyMpPethNRKoJl+6Mv1U3ND0hS0sGDBNaXjp13cJiKpNnXiFjkCss5Pk9F+CTm7oLxXjoa43CehTHq+0e4cWkrawpdfwB/76HS3GOfhP72oO6f8oqLvzpephi1D+VzbW11zQsWnWQUnuOzugKRCVs7ICaFpLdiqI55whyWur3dm+kZHR3cpGB5IrQSY2aW/ootKYmcPCwGSn1xqKIcP/5HuvI8Lw7O99zX90Ei+Y4O34EJdWGXKfU5cr2SLURi6kEYAFfbw/vqYlPB2pBx4lMnXN2hBr8cevgqUXYE2FN6AbhXmvYTS3rEETIYe/SQ8TOUatz/O50cPkVWQFOBeRGjm+RFIxAf0T8ORCeAJLDPWyOWZCi0BbYW+FUruzfyo+RwyREk8aQPNrZiVU6TqxgP7ik4a1F1w=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
