{% set version = "1.8.2" %}

package:
  name: ninja
  version: {{ version }}

source:
  fn: v{{ version }}.tar.gz
  url: https://github.com/ninja-build/ninja/archive/v{{ version }}.tar.gz
  sha256: 86b8700c3d0880c2b44c2ff67ce42774aaf8c28cbf57725cb881569288c1c6f4

build:
  number: 1
  skip: true  # [win and vc!=14]
  ignore_run_exports:
    - vc

requirements:
  build:
#    - {{ compiler("cxx") }}
    - python

  run:
    - vs2015_runtime  # [win]

test:
  commands:
    - ninja --version

about:
  home: https://ninja-build.org/
  license: Apache 2.0
  license_family: Apache
  license_file: COPYING
  summary: A small build system with a focus on speed

extra:
  recipe-maintainers:
    - frol
    - Korijn
