travis:
  secure:
    BINSTAR_TOKEN: fhPfSCyhYrG8HT3No1DJkPqmv2uJg0lCrLRD3ofbxQD25rqkYFAuenVZdqrvygZO/xsArjG81la0VdkZyeTMheSod3G0wzJ+eaYVz3FUcg8Jg2GEb4zjx7g1Tq6MisZwvPUEo80QAXiQ65gKGAI6Ux02eYH1JuRpQlrbQMSpYmdHyuncg7vS86f9xLizwki/InIq+ZgQxlqkK7tiaulDIRFAqGuCViHns+6rtE7ncfj+bMKwBwIR7d3UdkQ8lyGWiPxqIvjUIuJY+rHdhN4Vg9TP7eJim8u03L2KorsXhLjoVJWYlF5IAMQAysyzxXIzS8D80ph9eWUP8ZST1Hb+V40odlaSvLTI/8siIsxEfb9oVMaw3Tr/AMyoXFH75Onk4pB2dmEswA1lncZTLegDv92K6JBl+624iVDAqbh9cpc6PWajX9rEITdk8r/bYC3FzNYMMBY9QQc3/B1F6oxYyKRW6avzFZLjler71G1VfKZvs/NpRw2l4xGCWOfOHt7MDeVmCbnrcyreS8DVokeiesxnA5z/ap6rnCDc/2JfrZhM3ux7y03vFZBE8jKDpEnACNMhyiWonKUs25iAyDfRSdAdJGfrN5ScakzMXkh0+kiZPZAfklidVs/KVG4rl6lp4N/EgZ5aiwhq3RJ5q3VAVHuDYtJltzbRqJIOOuV8gII=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
