travis:
  secure:
    BINSTAR_TOKEN: M99kGr5BCuqRaeXe3i8zIFmbuIdmGrKLfj8HDBCQRBO8iZPqLXIStZSZ/88t1oPH0FkZdcDkVkbBCwfVSJqZzLm6+3ShcUwSSyU5lNEro2CCiXWhxyP+nABJEJxVtpkWx89+htJep6kvqhfWWoQaE3Y3Kjf+1Uo52xshk7AllRNDuchYfovFw3er5XQNdK2f+NlHRNNe3EFmmt1jXrP73wtAYb7GCiZfVwb5n/hqDTvkk/FO6HqGpCY54uGDCixFmpKsZ0Vuk5d8Lv48f20f/WADGGzTS0HsYmQ/ZwU0b/84KNYvj+8tLGws9arVI1Ka62WL+9qK3P/aNR2yYXIDWZHvM9J6Ft+vr8KCLZCIxWkhvmiHGqL+Co7raiYxStjS5IMWlQQYBtLDbVQkuE/L2Fa6qk5CKcT2Y06rsuN8ZiYJBRW9iL2voBIFwaWUJDLAgayi9sF2hZJLOBxD2j5tdJggr9aTULj/rFW7l65DWBitE1PqKlxzTekpB1ToyovZqtLvxuVVH76Cr9cvxzocZUp5Dy7JGqy67SpzSS7+1FUqTFaJQefLXx5rMjAvu4Ow7QzYUDwka8jZUd0c998vO46OYpn6n+73iG7ql+K3MsDtigvDckO9rZfMqjwxlTlhgUfFTIvs9uLDUnX06oAvu8fvCpuzIXIBdm4bZ4lJXl8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
