travis:
  secure:
    BINSTAR_TOKEN: b8Gcn5uhNo5OxLemGhFnOzcWsxiyWCa5d30H5mGjsWLfAI+OW/cnYpJdAInFeclPBdTzbKn1/bimMDTN9o46gL96/mIGnaQCJKgbtiQRd853NLUTlopjr/hMzmg8pkTWz/glQlp4EB1+S3QyOPMoYCxzGOMPUvuzcS6zU/8DLEifuVeDqnPWim5KlZv+/ivLzCHaAbEa+xjz2KAxpDl5I+M0YssrReWNcImCFFq0awKu73+7z6iNyCiOYRIWL/To8483hGI8zCJfgKzk0DopSE69bK+98GDzmTsjC45OcL6XHLtd+nz7WYsquWk6DOttIsiFTCmY/Dud7IXfS0Tlyi6zYl9wXHegkiREBAGonvEdRsYUXpDPbvczndwcPx55+6E34L7yW0LQBkMil5b6rmjU7G5Gw77i0D7GTuqdJabZNxWcd7QgZXB/7LoGfqq2bze80kCSHOp8G9msnln95I+Vv07N/STXGbUBmOem1waYp4l+phb7N+vqYF/03XPWN+1GNYsGuPLft/hrekyG0CVtUHYIovpbo00oUVjtZswp4vS04qSY+Okyy1nJc8bYEn2Dm7EMVxqvGXY1e+zS6Suatkx7vbtLm7vS/jCw13I8ICLoqoxAgTTj6B4Zzo8aziku7FBxaDzJTrPAZlw2upXq3h63Kj/yECVqSpHBYes=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
