{% set name = "libprotobuf" %}
{% set version = "3.6.0rc1" %}
{% set sha256 = "4ffd420f39f226e96aebc3554f9c66a912f6cad6261f39f194f16af8a1f6dab2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  #url: https://github.com/google/protobuf/archive/v{{ version }}/protobuf-v{{ version }}.tar.gz
  #sha256: {{ sha256 }}
  git_url: https://github.com/google/protobuf.git
  git_rev: 449e532b087e43a45ca6d8eae640a6019e547aca

build:
  number: 0
  skip: true  # [win and py35]
  features:
    - vc9     # [win and py27]
    - vc10    # [win and py34]
    - vc14    # [win and (py35 or py36)]

requirements:
  build:
    - toolchain3-rpi3
    - git                # [win]
    - cmake              # [win]
    - autoconf           # [unix]
    - automake           # [unix]
    - libtool            # [unix]
    - pkg-config         # [unix]
    - zlib 1.2.11
    - m4
    - python             # [win]
    - unzip              # [unix]
  run:
    - zlib 1.2.11

test:
  commands:
    - protoc --help
    - test -f ${PREFIX}/lib/libprotobuf.a                           # [unix]
    - test -f ${PREFIX}/lib/libprotobuf.dylib                       # [osx]
    - test -f ${PREFIX}/lib/libprotobuf.so                          # [linux]
    - if not exist %PREFIX%\\Library\\lib\\libprotobuf.lib exit 1   # [win]
    - conda inspect linkages -p $PREFIX $PKG_NAME                   # [unix]
    - conda inspect objects -p $PREFIX $PKG_NAME                    # [osx]

about:
  home: https://developers.google.com/protocol-buffers/
  license: BSD 3-Clause
  license_file: LICENSE
  summary: "Protocol Buffers - Google's data interchange format. C++ Libraries"

extra:
  recipe-maintainers:
    - dopplershift
    - jakirkham
    - jjhelmus
    - ocefpaf
    - wesm
    - hajapy
