{% set version = "0.11.1" %}

package:
  name: httplib2
  version: {{ version }}

source:
  fn: httplib2-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/h/httplib2/httplib2-{{ version }}.tar.gz
  sha256: f2176149e1e1c59e0520db62c925715018b787b2ae901358803bae5d816fda0b

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - httplib2

about:
  home: https://github.com/jcgregorio/httplib2
  license: MIT
  summary: 'A comprehensive HTTP client library'

extra:
  recipe-maintainers:
    - ocefpaf
    - sigmavirus24
