travis:
  secure:
    BINSTAR_TOKEN: PiGD75vCxdCRZQUvJ75biIKjra8uCI2wzqWaZkKjcOFl0LF6qeehdmRFVJPS2fiTTAA/3i+0subSiBibHjWm+V1Uo/R+GZrF/SNPeCOKzXjX/BJWZgzoOolK0rMyoiJQDjW/9OwVdzNJr020IxkUAIIB9tWxOfAkLsPq+a0F9u+fhMFemrPnmyGeMYNFQhcaz30yAdm2SXxDO4vC3n0uS0+Y5Ndt25lmQ9iLgfyIQdO0shEjOp9xTc5Ho+c+e3H2kTr/xrYqvMJ8KXXDOsF48vHsep4/YN0cFOIelMXRwwFrB823P4ODgj/jetwHAejBWQ126m7XOVpgYzapdNf0jB/+bJqefD21qWUIxMhGuL2r8TSq3AGMZqr2ryNOdvvLs6mwBkHkkD6xINjCs3LLaNUqE/2UvHYQ9Vfo+d5eKtWpTstF3rsvieAXthlEXJlYHxpEiSKu9G5o46F2S/oKOCaLE0oh5EPT19kyIjceY+D8TyB7m8lVhyQ0yUUATze1sKa1rIdADcFFjRApHrZ4YjRUv8NzpZGCi84inDty6LqvHuk7VhnlmsZc9EVRfEBbwnV5PV+Mi0ytLy5lcFB5vs7rf5ePAGvScRP7zHVt7ub1zWdtmRA7a0wrsFg//5/5CTPp/Viqon/Ih9JcL50KuRqIVkxjGsj/MsxiX0Bz5Vk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
