travis:
  secure:
    BINSTAR_TOKEN: VtQiL4Z3+kE2Z4ZMqwFE2W3n2bKQtmusqNVPgU0eYKLZCdeumbM87/HX/kajmY6q7f6HKjpwjV7mf+9B/+QoS6GKW5tIm86Zbf1ti9pz+wUuVL56GKTzpcyzVNPoKdx7gQL/M3WVi/vitENVAN6jjWvvVjayELxjXveMhgKR/kdnhY6KmOxKPBh+BpZ9AAmWMt2yn6muVPEVx2ptAWYvCaZkDmmIqoanuHjh+vvcOAnxdOQjl3gzTMcDDdRFknZ5GdLvhweanyTJX2eJ9vLVE5k8Vd28RjRjaT5KUZf9CIVmiS0wPRN7YN3Lz1mduEpVJ2tDvoeObcbxNRXuToU5eqiJbliEnP93AoJPrNi9neH9l24fWWQCwSADmNVxfk8QT9rB0etjKu3JOAxp8w/5xIegsPz/Sp062+CCHBNJZRe3KkM6eA3Trd2S0ZXQI7zS9qnVYLeP4rq/49hDbPY5RCWvQI5VFFjiWDa0KjpDXoVoqn6444LF7Qp5ojDMvl3sHsQkex1txYag1dWvhAMdHCPANXcsBh/RgkH8Bi6fCNScvuTFrnCxlkOG0YmIE/Pzfrq6DzOqiTxvS0Nwxqu98nmxQS6LPCyYb9kkS/jijsION+kflaDPrUVyR/y3E1jgdtKOLCE6doOkqwBOcuTirnxN8NNQ0R3aN5IinNgORDc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
