travis:
  secure:
    BINSTAR_TOKEN: F0/zX9Yv5cl0Kz1P7tQDazZpI1TppPq5xBSgz21EY8nCaubBSErdjgU3XRuwfaYO18AMBbz28oAD1YL6fCE8BM5PwD3/6nC+OmOytxCGyJ4RtecvAPNo994YX9dwCh8qaXr2i/lHPl3haotS88RVCQcA8FpyDyfxCsZPW0y6XDQK3wk3jfOPhQ1Q9U6qJRiirO2bSFIZ1ooycCj/Aa8jYEepCqFHRaEmXd51yo1J4LEFxwA8g335UiP8nffiV/Sn+2sMPB8T4r+bCou1Ku0m1KeCDaExKRG49WOpFzKOCk3QYg35JrHn7Sc2sbGTV9mQ/iYu+4aE0bL6c5Ryev4toDfio1wQ1PsWeyR8ZhHrn2Ukg5sd7sExlVroniXFANxfxxE2Ud9lDLuRS7ySPRvxMYZ00WHRQkpPH/+i3N3NNv4jaBkhQ6go5W804K0LuqvAYozjodL4wqO0TxDhgWgNTWBTIiLR346hWwivzmqR0KSEBMvn+Q7PKq89TYEpmML453sUMsgI6FjjUKBuRjZ+euWrABAiSLa8ii+BKQvyPOK3ZDR6kcdsIitEGQK4Tmwm61+qLNi+Yv0IUxrYhRkHVnvtMcBsKi5nCn1tbzf7rQOBbvS93SunqUtjE17CLaYwM+6ysTKz+bsS2Qd/ZmBfEK9aoB6URvkZ2d9XB5jqtVk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
