travis:
  secure:
    BINSTAR_TOKEN: DM2d2pxZ8qz78KNRRQnNr9WCzmy9qFtBMolv0Wxt9OtxxT34apzbvW4HvvoewJbqyi+eTQkVbZdIZhmsKfSPtdDmFjkUwyPFu5r8rUXYjG1MqtfSwFGHFVar0MHSIiKgz7exBMAQma21NMNdUBGN8tACcwa/NMs7z6pue+oJw8eyGD3q3MGjlY7vo7yX17ssb+xSn210ZRH9FWALJSszhpNqMgUYvC5j8GyDx84Mp84bGEzzBWn50V+Nu8GUKkk9SzKYaa7yv7+8LO/jIdSaXaJaM9Y1gOjQg3K1m/cPT0LdU9gtbErPt3aURf0hZr84SVvQAhZZkGj27oD35ut9f/8UZRey3iYjV9OflXSZ2vsiK/k4WDlIkekmejz6iW/08JymkGuTXpOFgl8QPkCBx/JXzyarboR2gUNNRlISjj2Tg6tOZ3bkzzpJQjpOJSehRKouD4zCBzXERkK1Nj8vrYKGQkKMLN2uuzmzIA8jNh0xf21d8b5yqmwkBQu3kFUUdqbQrUHpb8/CYW3sObnraC9MDn+/hEJzfQxGnR1KMxwualxlCDy7W4VNLUr9AGIzBwySnKRsCjj0LNtI8BAjdkyW+k37x0+10bHrH9H9FAPohnZNfp1+qu7B+b0AryUSjO8cG4TsjNp0BGf0ge/XwRsyM2+SnE4N5rR5j6mEI8g=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
