travis:
  secure:
    BINSTAR_TOKEN: N0FWMsBFRGPPKv/tH3p69E0Wj23qzef9w0rKUrjCaZiCzPHE4LkaN+bVJ1J61dnKY55zjoUZH3JbNt1yGvAvNBAb6OIW2pBZ0IJZsNTyJFqMUnI5zPO+tIdd+QSlDwPuaHpTuyQ+xNpt+MDc+SnPhAxUWx8QxrhI0K4Jvwr36C/Yi4oN61v9dNccm++4HnF5n9YJtCvwaNkMqCP2uIP90ClMICAvpYXy3Ci/z7SLOjwEYeQ2DxvACJO3SYn7ksGirQxA1Oe8wi0g5hafzvXmFTLDDUN2SM6ClUmNO7n6MBX+rOSELOihfINU+Nk9lMHsZ6aVE01JXucsRjhXv6Xhp4SuYJ5YXttzIFsF86/qA6RNQHTdY/TRy/sZRIB993vRnbDnSHWAwOY5LFsCwt5H8qElegkNWsykAxtXTEFjz0Ust24IvKdQsdIxQBqLzWU0gMmKULP9zGAQ2eTQ3ZxLS6LZ5YfVJbrgAJeW25xjUYNJpy9mdly5l26bczHBcR1Ipn5dm6XBsOjeVL9ThOgXL8oNcaOusVwoC1oFZpKQLm83szHxP7nr8OwN9t1X7ETpU3FHPu7lT7mrZtXYOvZO6Z3ehcI/xUDW7PT60/DwTb5zPFR6gG8MjSbpq9NgTQn7TdPoF02EKLKINctSSOuufV6ZvG++ER2aQ/ynGlPPyyg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
