travis:
  secure:
    BINSTAR_TOKEN: hBGqQbT/4LkFLWJOAQ5Ia1MdAGTfRtSQNoeBOKfLxPUkGQyCAp6lbzUg2aRoG8K2tRnBnhhhyz1HS1kpAPmoscB4ekYhhgjimoZJICdKM6YJ9YB7IcBmYDXrAs5f+45CiJ5ma1NgNjjYowTLmN5DgJ+CbVE7q/i5OUtq2CrIIBNaG0D+SfHxa2la7aMKMT0BTa+EWZ5Csl8BBYUfIz9Wh0cX1baTdI9/8nVITmip+hG5lfJvJczP0KcPGiYAtX0k5Cw91IL2nuU4IXRy9D0JVMpTxJv8dBgD2l4CtvwCdOGfILIHuePcyAahMM1JEepMKVTADdSnvCaG+LscRUQcy+b2aFmBPFKWZYy76Cz4V9PVQv3X2oca8Nv1zJSOcqiVP/zcGY0eVP1gElWXmbFx7BpYWEd9KLnYBl7zIuGTij5lwb9sxpJQd2tVIyHlR6y13/tBiy2LzWg+/RO3XTrVd3nzqIxTFFHNkyvpOD51u+88nY8oAka3dkOWh5CobDE+XYBnQC3kDGgkpYSy7oLu12ntTiMP3SnQ+3eP1V6D7LyCF32PsIElJ70Qv9oVXWI8+PaeyQ3FbPtJ/ZpsJo9xVCWpERUvzOYkKyin/5P4o1DjBGklwSZ/dJUv9PWu0z8FX+J2XQlGuCnjgv3KEVtguQ6V7fHoIqdbnVk34R3El6c=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
