travis:
  secure:
    BINSTAR_TOKEN: T+Z5MBDeonWIMTSlwoGWJ2IXgwmLjLYYfkBY8zhoz5tP1FcIULJrAi/gULQSuSRMbZ6osRgVubMhzz+RvBOT9KEDSNLbqSuc08rmu7CXNxAcBJ2vxhHRO6lYPX+YRy9lYD4WWJom7wi38QswiYnOiMao5Wt07vlSG3bGWAR0m2TX0RBZ2KH6GCVZ4WKfEVA3gLke+o/1bjeA7MW9YBBwJ6kmQTFZrBYBx4YIZwYjPpdVIzh7FF+OmMlUok5JaH0pQch2YmvvcZlg+aYhp2as5e0Pbw3kISB864hNuvEKCyICUGdVy9UuZgewzqGemjyzP6LLHg95LfDafHEaFIYAakvMKnmLvnNXxQ4pSkLkT6CT5Vho4cTq5EsrNjVW3EXNbPwjJkDorYw46xzUFEFASbxk5wZCK8FO8/OfTg+e62WqNnEUA8u7nWH3tecsGiZKBpjdjp66VIrv/0Gac2K+OXuR+bNqezelxworIULxiSJ6f36Vfy+M+4sa+YSEIYp7m591vyl/KNklvH6+VPuiBV/iIT/nMNFN6578ZmIaxtQvdGLgmsnb3txcDVfPEef1YPCGTLtkAnuJF24XJkpd/vp/xdzfBHQHd/VnkegOYrYNZd7NS8HGyWna9e0FJfdGXtF9Qb1dEJlNPKpzlXxojyx7cqVhQo8hWkRe71X3goI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
