travis:
  secure:
    BINSTAR_TOKEN: Kywb827VqQQ+4Wc4GsSZAKQsA2rGJ3yHahY5PuHpV0kQjHGue2/jN4KmXorzlric0MTWPmPQMoLBxtQGa1IjSQ7yQaKbv+uNLnXZW/YaQGy+yOWNieBJ7HStq8KT7Ivdbeniyr06Q6tbf1O3QUQjnqaWFrFrT7EI+MzdoYK42vBRIROWgiQHpuHKmi8sgatzAUfdNIv6xupUB9MeQIvTa23btMjgldYKu/Vr6eJgxFKGceI0sBm656rMI5Q1GTLJUNAHQjlICTSxrEQgMZFHD4Qu+pL1fbhlUGrdjMLuvzeytyNoCrmbdiepkVVCmb09lnePX3alCQ3XWSOZbTqi8dyJW9jQ0ojbjHBhH97/4xDAW7cRaMeeZvV36b/7eVqSl/h43DPkiuPCZpyVMgGNThQ7Y5ml9IoxHS+zdAIIUkjiydViYdKSFnJ8ywhT/QOYKdPoqcB9Vy12uNLhPEhVNsIl2Ivr3Tb8GKcshcHdnZy1VQ00ziZyq91hn94DciifLAI1N93sZBtEIYqOh8EZOCp9uEzvyRlwtSyfEz4x899GC+3SAplImQhlypEYIAfInYtU1BFwWbOtgrKG6CUVTtbsS+muc96JlZDIhshoHzakIzzyo8V/fOGzJsEOB/TDJx3P6CMm+IG1V8aKZxqbZHiiDpHboL75XfNxUfXLk1g=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
