travis:
  secure:
    BINSTAR_TOKEN: OUYkE6QlO473UwSxYOjrQULGI2CsU9tCxC7mUDqD1Ry2jbJwHSvgQyDszKLJayT9juWdb4VzQf7zCYBiX4FDUFyNA3vQFd5axlytm7H9zZb6jGTdShGWLC5KFHKp8QG5Ulaodgg5EWisA0d6dEOaedMTIVbZtRGhiRlYR159ncypKtD9yFzWde4O6mZgvvKEE/aK4QTSyr01353IrogrWJhAk5+O4stWs4llWzLlryp0qExS8J0/eO8k68ToMuLVRtvln9qSc+PbiXtYU1oh/o5AoteMQm7vikafDVdFtTNrOhLYTsOQy4dq/BFu2M8JwXrIJwLg+nEF4s5GifYB1n/5pUCV68uAudlBW2zgC88wzQAZRyC0vwI05TYegyCqmXLddPN5OdGURY/fpL58ewkiCh0kQ6KfWPuJYc6QQqwYqmY2/9SzruDHgTZVDtNEe6s4mzE6Y3PrhT9IoAMUvV5tGOZ/rOYd1+hGF11eNAJY1BTO+jEBR1caEH7NU8q4TLK4EP0j/8g+60soapVrtP13Zlh34BzjolhbR56wt9ldmxkQTac6U3UFCLNmWq2DMwLtFLG6W7XCr3UZSEbo7EyD6Te/ck9hofZXf4XzPNhCEB6cCAVWB6l4rFaxZhr9YKk7Z96oEiDuXWVayTHHCW801D4P++XJOLwI9UuDVRw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
