travis:
  secure:
    BINSTAR_TOKEN: 0a/VPuK52rD8gJqcLVamGgGYtuXLSgAU9TJRZnZ059N5Z83jik2bAgQF9Rnyyd66M5CpSzIE9H1GzUM4FKDCnWStALrEgHAVcU4LPXX5EIqfduoHvxVKaFWrARlLOodiZNRYAl9JiAZ3vYDTK4ZTD4tJ4B02QiBRAOZIMdlAKePutbPLkQulmSxEnDTvogm3sDAJR5gsNgoI5Ev7+z7n6ugqs3uLQg4Q1yWL94IHWq5l0sefQoVADOrY7utuF3tlWu7fql2rbEbRtcf4oEh8gqj4jwY/dfxfxg0n1ZzbG0yNeUE46tEf/KBQUz//Hjz6lMzg0oZaXfU77rArYWldtpCud6+No4CBC7Y7KQE6XrFCm6bOaJAUSSBRf3ZG5Vl6Wnu/7+cKNqUghjiY3LGjTNprBrXZyFxzLDEiizpF42ZWtdhH0U4UskrtpTWx7XMLgbfPFjAFatAV4W4eAzrI9yZ0j7Nn1BEmcJwpbl+2VSqKyw4RNEYpRn8cf9ugPhNH6rtiB8EIed46sAzeUP/d5u/2UR+28JZI/f++6nk3UzSAbZUoF+emQFagL0jTWKZ1pDk7mveQFUPVMsilaQ7Rg5N2UYhd/rp85r6bUs5ZrzpZ96/S31P9lM51Kj4e7JVxC0tTb9+2pKFeMGbE2DOcOhg725LNUh4fp75B9CFO+LM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
