travis:
  secure:
    BINSTAR_TOKEN: raKfX2FnvEjvot6KACOjLzCcdBiInS4A16LNghQsw11xfAvLSYMy35vmIq2r+19SAoOKABpItCbNyd7N7Lo76+sFW35ga1eq5X+QSZbvN6Q3oqbV8XcSI565gbzEJ5/5zDlxcgnWZ+5vu7mtg1dQaqdRkSpNTQFowCvV3TfoKd0wfOEABXNSGhB3rguducpL+VhMXdEcgI7+5Z+B5RL20D4FTHUxajRk4xEQsLzGi1PwCtVYObSEjAJi2bmDcYeW6F6uVG1qBrfJGuW0HXWWgOHRJuARfzVecNMJ6zUVk1BV4PZrxM99ZrS3BpUcDOXPUsGmUAHXM/RBvDi5JL9/9glkoYvqO2LiM7d72EY67H5vbGKsQJt0ucBaPINmplhni+ufAfpOsS8Xoh7+T3H0Q9ncjzVS2dQa0uvM00FvsQ16zNGmFxhEeZlA9QZHzkxxVWLM16S8fgQWOus5IrEgzuRcxPCrwSxpaSLhcmRRsw6iCen/aUJAUAE1j41OloR+y+rmpU5NMwJvv0PYwiPmKCSc6/dlgPgXsBm8z+HglyjClaiCbvPLctopj6eSoRP6z4dVuV7PjnIQBBLiOYwsiWTho8UaC30o73V2S1DMR4Xj35+WWIV0no7rytQ9Grzk9H37igPXF7+I1thYaY6fXdWDe/oR+SWJ1sM8/eCggBg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
