travis:
  secure:
    BINSTAR_TOKEN: Mzn+XnvgEjoduBnrG227rZtZc4zRDXYoEdyGXldluU7VWWt6nnXs1V57jp6TJt7lhBGwuFcsk61vhqMThXUgeHPey2CehGokgp+1/aqKwiFgNHEq3hYN5MjcIyci5R7ktXHoa0Rac+bp5zM0nBRFqM5M/GynueNR62HeSUlOQ7Wv6xmtLe922LJ9IsoP/nELBBxxGaWcIyRI60RSX7AjUhC64dXiIvbt9GKPyQ8Ff9xZHx4kMVdL3datzOdYn1OdM22INz/AYzm9xOIEre5QJfRZXGQe931KSbsgXYKqDyBCKHKnTHlad7yAPUTk4avuhcYOCyFm9VHTguXZP89a2qySiXNO+atEsFj4jioabqZ/1n6phltlsz18+2K+ET+jlZgsZY2Rm7esK/X5JISvEXT712AEiJJhs7AbcgOxX9x424G7mRHueTUVp9PzA4PvHj8qxcOrbjSqvU61U7roP5HQamnVneUBbpG7DFwsjhNFPtY7bPqXBeGa/b/XaIqmId6TzmePFAmATjrApfC6FfY7o5s3zBZME76oGHZmbNX74uUosMr6t2gNAM8sls5QpgtnG+3K321AYdbr68kkIsm82/NFuNsP96FO717cnCWkMeB++TWoTyggEBRrNcxZO2q6tGPIQI00sVA0HjREoByMTOb2eUc9AApbln8lkQo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
